### ISSUE TITLE
Bug: does not respect reloadOnDisconnect when set via injected provider

### ISSUE THREAD

**Issue by KosGrillis** [coinbase/coinbase-wallet-sdk#1012]
### Describe the bug

Disconnecting from a Dapp via Coinbase Wallet triggers a page reload when the injected provider (not SDK) has `reloadOnDisconnect` set to `false`.

### Steps

1. Retrieve injected provider:
```
const { ethereum } = window;
let eip1193Provider = ethereum;
if (ethereum.providers?.length) {
    ethereum.providers.forEach((p) => {
        if (p.isCoinbaseWallet) {
            eip1193Provider = p;
        }
    });
}
```
2. Set `reloadOnDisconnect` to false:
```
eip1193Provider.reloadOnDisconnect = false;
```
3. Disconnect from Dapp using Coinbase Wallet browser extension
4. Page will reload

### Expected behavior

Disconnecting from a Dapp via Coinbase Wallet browser extension should not reload the page if the injected provider has `reloadOnDisconnect` set `false` or `undefined`.

**Comment by sam41306061** [comment]
@KosGrillis , is this bug still open?

**Comment by KosGrillis** [comment]
@sam41306061 Yes. The bug is still present

**Comment by sam41306061** [comment]
Hey @KosGrillis , Do you have a dapp project repo that I could reference? Just to help with context.

**Comment by bangtoven** [comment]
please try sdk 4.0
