### ISSUE TITLE
Bug: Buffer is not defined

### ISSUE THREAD

**Issue by jm42** [coinbase/coinbase-wallet-sdk#1108]
### Describe the bug

Buffer is not defined

### Steps

1. Install `@coinbase/wallet-sdk`
2. Start dev environment
3. See error
```
Buffer is not defined
./node_modules/@coinbase/wallet-sdk/dist/relay/walletlink/ui/components/QRCode.js
```

### Expected behavior

That a frontend library doesn't use a package from a backend engine.

**Comment by jm42** [comment]
What's wrong with using [`btoa` and `atob`](https://developer.mozilla.org/en-US/docs/Glossary/Base64) functions?

**Comment by mujju834** [comment]
iam trying to solve this issue.

**Comment by jm42** [comment]
Excellent. If you encounter any "Unicode" problems, know that [MDN have the answer](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem).

**Comment by Mandog1120** [comment]
5dfc255e677a0ec689e20ec0c7881a726454c546

**Comment by bangtoven** [comment]
please try sdk 4.0
