### ISSUE TITLE
Bug: Universal Link for the deep link is not working 

### ISSUE THREAD

**Issue by basitcubix** [coinbase/coinbase-wallet-sdk#1110]
### Describe the bug

https://docs.cloud.coinbase.com/wallet-sdk/docs/deep-link

### Steps

I am using the universal link `https://go.cb-w.com/dapp?cb_url=[YOUR_URL]` from the documentation to redirect to the coinbase app but its not working properly it is redirecting to another page as mention below it was working fine last week 
![Screenshot 2024-01-11 at 3 10 46 PM](https://github.com/coinbase/coinbase-wallet-sdk/assets/132077089/5c1405d9-e3c1-450c-b15f-2d31c6162370)

### Expected behavior

`https://go.cb-w.com/dapp?cb_url=[YOUR_URL]`
this link should be redirecting to coinbase and somehow its not working can you please share the new link or update me what i am doing wrong

**Comment by bangtoven** [comment]
hi @basitcubix 
we worked with branch.io and the issue has been resolved now. 
thanks for the report.
