### ISSUE TITLE
Bug: Incompatible with Strict CSP style-src

### ISSUE THREAD

**Issue by dannyDNS** [coinbase/coinbase-wallet-sdk#1122]
### Describe the bug

The SDK doesn't work without 'unsafe-inline' style-src in CSP

### Steps

Set a CSP without 'unsafe-inline' style-src and try to use the SDK.

### Expected behavior

The SDK works without 'unsafe-inline' styles.

**Comment by kakashigr** [comment]
Also if you're using the "Cross-Origin-Opener-Policy" header with "same-origin" you need to change to:
'Cross-Origin-Opener-Policy': 'same-origin-allow-popups',

**Comment by bangtoven** [comment]
please try sdk 4.0
