### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by juansalvatore** [coinbase/coinbase-wallet-sdk#1156]
### Describe the bug

data is undefined

### Steps

A dependency I use uses coinbase-wallet-sdk as peer dependency.
It's using: `"@coinbase/wallet-sdk":  3.7.2`

And I just got this error:
<img width="1150" alt="image" src="https://github.com/coinbase/coinbase-wallet-sdk/assets/11010928/5650627d-be17-49a9-9f4a-d190d761518e">

### Expected behavior

I'd expect the library to check if data is undefined before accessing keys 

### Version

3.7.2

### Desktop

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 OPR/108.0.0.0

BrowserName: Opera - Version 108.0.0

**Comment by nateReiners** [comment]
Hi @juansalvatore thanks for the bug report, but we don't plan on making changes to old versions of the SDK. I recommend upgrading to v4
