### ISSUE TITLE
Bug: @solana/web3.js needs to be update to 1.77.4 or later. High Severity 

### ISSUE THREAD

**Issue by jtardioli** [coinbase/coinbase-wallet-sdk#1196]
### Describe the bug

There is a security issue with your dependency  @solana/web3.js at v1.77.3

### Steps

Due to many breaking changes I am using an older version of [Wagmi](https://github.com/wevm/wagmi) which uses an older version of the `coinbase/wallet-sdk` library. There is a security issue with your dependency @solana/web3.js at  1.77.3. [I  raised the  issue with the wagmi team and they told me to reach out to you directly](https://github.com/wevm/wagmi/issues/3836#event-12552584832) 

![image](https://github.com/coinbase/coinbase-wallet-sdk/assets/85530348/e2190a4c-aec6-4346-978f-b86d6bdea993)
![image](https://github.com/coinbase/coinbase-wallet-sdk/assets/85530348/8c621463-945c-4058-9141-5ec0ec660f8b)

### Expected behavior

 @solana/web3.js needs to be upgraded to 1.77.4

### Version

3.7.1

### Desktop

NA

### Smartphone

NA

**Comment by nateReiners** [comment]
@jtardioli This has been fixed. I understand you're facing upgrade friction, but I recommend upgrading to wagmi 2.9.0 or higher. We expect devs to upgrade and don't plan to make changes to old SDK versions.
