### ISSUE TITLE
Bug: Error in Coinbase Wallet SDK Documentation for Smart Wallet Creation

### ISSUE THREAD

**Issue by sflanary97** [coinbase/coinbase-wallet-sdk#1254]
### Describe the bug

The documentation on the README here: https://github.com/coinbase/coinbase-wallet-sdk

### Steps

Following documentation for Wallet SDK Version 4.0.0-rc on README, or [Coinbase Smart Wallet Docs](https://docs.cloud.coinbase.com/wallet-sdk/docs/sw-setup):

1. Install @coinbase/wallet-sdk version 4.0.0-rc.1
2. Initialize SDK: 
```
const sdk = new CoinbaseWalletSDK({
  appName: 'SDK Playground',
});
```
3. Initialize Provider:
```
const provider = sdk.makeWeb3Provider();
```
4. Request accounts:
```
const addresses = provider.request('eth_requestAccounts');
```
5. View error:
```
ERROR
Expected a single, non-array, object argument.
    at getEthJsonRpcError
    at Object.invalidRequest
    at checkErrorForInvalidRequestArgs
    at CoinbaseWalletProvider.request
```

In my case, after inspecting the `util.js` code for the `CoinbaseWalletProvider.request`'s `checkErrorForInvalidRequestArgs`, it seems to be failing from this line:
```
/**
 * Validates the arguments for an invalid request and returns an error if any validation fails.
 * Valid request args are defined here: https://eips.ethereum.org/EIPS/eip-1193#request
 * @param args The request arguments to validate.
 * @returns An error object if the arguments are invalid, otherwise undefined.
 */
function checkErrorForInvalidRequestArgs(args) {
    if (!args || typeof args !== 'object' || Array.isArray(args)) {
        return error_1.standardErrors.rpc.invalidRequest({
            message: 'Expected a single, non-array, object argument.',
            data: args,
        });
    }
    ...
}
```

The documentation in this README as well as [CoinBase Smart Wallet Docs](https://docs.cloud.coinbase.com/wallet-sdk/docs/sw-setup) pass in a single string argument to `provider.request` as 'eth_requestAccounts' but following the [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193) specs, "The Provider MUST identify the requested RPC method by the value of RequestArguments.method."

To properly request accounts and view the Coinbase Wallet pop up, the documentation should be updated to `provider.request({ method: 'eth_requestAccounts' })` instead of `provider.request('eth_requestAccounts')`. This update resolves the `Expected a single, non-array, object argument`

### Expected behavior

Coinbase Smart Wallet should open after following README docs.

### Version

4.0.0-rc.1

### Additional info

Version from documentation 

<img width="731" alt="Screenshot 2024-04-30 at 8 40 44 PM" src="https://github.com/coinbase/coinbase-wallet-sdk/assets/11082308/dc22323f-090f-4fc2-abad-470f223ec48a">

Produces this error:

<img width="731" alt="Screenshot 2024-04-30 at 8 40 44 PM" src="https://github.com/coinbase/coinbase-wallet-sdk/assets/11082308/1a9da59d-f6b6-4132-a1d2-a710b5c2699f">

Proposed Fix:
`const addresses = provider.request({ method: 'eth_requestAccounts' })`

Produces expected wallet pop up:
<img width="435" alt="Screenshot 2024-04-30 at 8 43 04 PM" src="https://github.com/coinbase/coinbase-wallet-sdk/assets/11082308/b4bbaa56-8a04-4f02-b6fa-5eb972ef6494">

### Desktop

Browser - [tested on Brave, Chrome, Safari]

**Comment by Josh350Hops** [comment]
Hey From Joshua

**Comment by jakzaizzat** [comment]
@sflanary97 Try to pass the object inside the request function

```js   
let response: string[] = await provider.request({
  method: 'eth_requestAccounts',
 })
```

**Comment by nateReiners** [comment]
Hi @sflanary97 thanks for catching this. This was a typo but has since been addressed. Also, we have new and improved docs here: https://www.smartwallet.dev/sdk/makeWeb3Provider#usage
