### ISSUE TITLE
Feature Request: SmartWallet - Allow owners to be initialized implicitly at time of setup

### ISSUE THREAD

**Issue by Silur** [coinbase/coinbase-wallet-sdk#1275]
### Is your feature request related to a problem? Please describe.

While the deployed smart-contracts support the whitelisting of additional owners besides the signer account, the SDK itself does not provide a way to clone the contract using the factory with the owners parameter.

### Describe the solution you'd like

```js
export const coinbaseWalletSdk = new CoinbaseWalletSDK({
  appName: "An Awesome App",
  appChainIds: [84532],
  owners: [address1, address2] // would be nice to have this here
});
```

### Describe alternatives you've considered

Currently, approving an additional owner on top of the first-time signer has to take place in a separate transaction, which is contrary to the general "easy to onboard", "set up in 10 seconds" narrative.

**Comment by wilsoncusack** [comment]
Thanks! Is the idea here that keys.conbase.com still creates the account, and you can pass owners? Or you want a full SDK for interacting with the smart contracts directly?

**Comment by bangtoven** [comment]
I apologize for mistakenly closing this feature request issue. it was an error on my part. 
reopened the issue and will review it promptly. thanks for your understanding.

**Comment by bangtoven** [comment]
if i understand this feature request correctly, sdk is not a right abstraction layer to offer this. 
sdk constructor is to define dapp’s configuration, not account specific parameters.

**Comment by wilsoncusack** [comment]
> Thanks! Is the idea here that keys.conbase.com still creates the account, and you can pass owners? Or you want a full SDK for interacting with the smart contracts directly?

@Silur is this right ^

**Comment by perttrus97** [comment]
0x5f38029b6a3416b7a866eefa15cf080ee80c9f48 here is mine adress

**Comment by wilsoncusack** [comment]
Closing due to lack of feedback

**Comment by dropkick1325** [comment]
My email was hacked dropkick10113@gmail.com my new email is graciejor26@gmail.com  can someone help I'm locked out of my email
