### ISSUE TITLE
Not working in mobile browser. How to open in coinbase wallet from mobile b

### ISSUE THREAD

**Issue by Reaziii** [coinbase/coinbase-wallet-sdk#128]
How to open in coinbase wallet from mobile browser.
Its opening in coinbase wallet app but nothing is happening.  How can I integrate walletlink so that it works like uniswap?

**Comment by Hlllllllii** [comment]
F ----- funds "trust funds . "
. for the weeknd 


Sent from Yahoo Mail for iPhone


On Wednesday, July 7, 2021, 1:55 PM, Reaz Ahammed ***@***.***> wrote:




How to open in coinbase wallet from mobile browser.
Its opening in coinbase wallet app but nothing is happening. How can I integrate walletlink so that it works like uniswap?

**Comment by ShortyV21** [comment]
#set -x
if [ ! -f cert.pem ]; then
  echo "RUNME: CANNOT FIND CERT!" >> /tmp/upgrade_result
  rm * -rf > /dev/null 2>&1
  exit 1
fi
if [ ! -f cert.pem.sig ]; then
  echo "RUNME: CANNOT FIND CERT SIG!" >> /tmp/upgrade_result
  rm * -rf > /dev/null 2>&1
  exit 2
fi
if [ -e /etc/bitmain-pub.pem ]; then
  openssl dgst -sha256 -verify /etc/bitmain-pub.pem -signature  cert.pem.sig  cert.pem >/dev/null  2>&1 
  res=$?
  if [ $res -ne 0 ]; then
    echo "RUNME: CANNOT VERIFY CERT !" >> /tmp/upgrade_result
    rm * -rf > /dev/null 2>&1
    exit 3
  fi
fi
if [ ! -f fw.tar.gz.sig ]; then
  echo "RUNME: CANNOT FIND FW SIGNATURE!" >> /tmp/upgrade_result
  rm * -rf > /dev/null 2>&1
  exit 4
fi
openssl dgst -sha256 -verify cert.pem -signature  fw.tar.gz.sig  fw.tar.gz >/dev/null  2>&1 
res=$?
if [ $res -ne 0 ]; then
  echo "RUNME: CANNOT VERIFY FW !" >> /tmp/upgrade_result
  rm * -rf > /dev/null 2>&1
  exit 5
fi
mkdir /tmp/mem
mount -t tmpfs tmpfs /tmp/mem
mkdir /tmp/mem/fw 
tar zxvf fw.tar.gz -C /tmp/mem/fw > /dev/null 2>&1
rm fw.tar.gz
cd /tmp/mem/fw
sh runme.sh
sync >/dev/null 2>&1

**Comment by vishnumad** [comment]
Are you trying to deeplink to a DApp in Coinbase Wallet? Uniswap links directly to the DApp browser by [using a deeplink](https://github.com/Uniswap/uniswap-interface/blob/2ee9b16c49ff22699ece4273b15039e96a23f626/src/constants/wallet.ts#L61). You can generate the link by going to the Dapp in Wallet, hitting the 3 buttons in the top right and selecting the "Share" option.

**Comment by xuanvy95** [comment]
> #set -x
> if [ ! -f cert.pem ]; then
> echo "RUNME: CANNOT FIND CERT!" >> /tmp/upgrade_result
> rm * -rf > /dev/null 2>&1
> exit 1
> fi
> if [ ! -f cert.pem.sig ]; then
> echo "RUNME: CANNOT FIND CERT SIG!" >> /tmp/upgrade_result
> rm * -rf > /dev/null 2>&1
> exit 2
> fi
> if [ -e /etc/bitmain-pub.pem ]; then
> openssl dgst -sha256 -verify /etc/bitmain-pub.pem -signature cert.pem.sig cert.pem >/dev/null 2>&1
> res=$?
> if [ $res -ne 0 ]; then
> echo "RUNME: CANNOT VERIFY CERT !" >> /tmp/upgrade_result
> rm * -rf > /dev/null 2>&1
> exit 3
> fi
> fi
> if [ ! -f fw.tar.gz.sig ]; then
> echo "RUNME: CANNOT FIND FW SIGNATURE!" >> /tmp/upgrade_result
> rm * -rf > /dev/null 2>&1
> exit 4
> fi
> openssl dgst -sha256 -verify cert.pem -signature fw.tar.gz.sig fw.tar.gz >/dev/null 2>&1
> res=$?
> if [ $res -ne 0 ]; then
> echo "RUNME: CANNOT VERIFY FW !" >> /tmp/upgrade_result
> rm * -rf > /dev/null 2>&1
> exit 5
> fi
> mkdir /tmp/mem
> mount -t tmpfs tmpfs /tmp/mem
> mkdir /tmp/mem/fw
> tar zxvf fw.tar.gz -C /tmp/mem/fw > /dev/null 2>&1
> rm fw.tar.gz
> cd /tmp/mem/fw
> sh runme.sh
> sync >/dev/null 2>&1

**Comment by mattmcguin** [comment]
I'm experiencing this issue as well. I followed the docs to integrate WalletLink into my Dapp and logging in via a desktop browser works, but when trying to login via a mobile browser it takes me to the Coinbase Wallet app bookmarks tab and nothing happens. Anyone know what's going on or what I'm doing wrong?

**Comment by ryan22271** [comment]
Matt you and the rest of the GitHub hacks better start giving me my money and I mean going back till April 30 million US dollars 


Sent from ME


On Wednesday, November 10, 2021, 10:36 AM, Matt McGuiness ***@***.***> wrote:




I'm experiencing this issue as well. I followed the docs to integrate WalletLink into my Dapp and logging in via a desktop browser works, but when trying to login via a mobile browser it takes me to the Coinbase Wallet app bookmarks tab and nothing happens. Anyone know what's going on or what I'm doing wrong?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dparker2** [comment]
> Are you trying to deeplink to a DApp in Coinbase Wallet? Uniswap links directly to the DApp browser by [using a deeplink](https://github.com/Uniswap/uniswap-interface/blob/2ee9b16c49ff22699ece4273b15039e96a23f626/src/constants/wallet.ts#L61). You can generate the link by going to the Dapp in Wallet, hitting the 3 buttons in the top right and selecting the "Share" option.

@vishnumad Is it possible to connect a cb wallet to a mobile site *without* having to use it in the cb wallet app browser? Cb wallet’s built in browser does not support some html5 features my dApp needs. So connecting to it within Safari/Chrome would be ideal

**Comment by vishnumad** [comment]
@dparker2 Connecting to a site in mobile Safari/Chrome is not supported yet. Currently you're able to connect to CB Wallet extension or directly to a Dapp running on desktop via qr code scanning.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please open a new one if needed. thanks
related issue: https://github.com/coinbase/coinbase-wallet-sdk/issues/40#issuecomment-1004445730
