### ISSUE TITLE
Bug: fetchRPCRequest does not return server errors

### ISSUE THREAD

**Issue by devnext21** [coinbase/coinbase-wallet-sdk#1337]
### Describe the bug

`fetchRPCRequest` in `provider.ts` only returns the `result` field sent by the server. In case of error, the `error` field is ignored.

### Steps

Call `fetchRPCRequest` with data that should return an error (ie eth_estimateGas when the caller does not have enough funds to execute the transaction)
```
fetchRPCRequest({
    "method": "eth_estimateGas",
    "params": [
        {
            "data": "0x...",
            "from": "0x...",
            "value": "0xd3c21bcecceda1000000"
        }
    ]
}
```

The response sent by the server will be:
```
{
    "jsonrpc": "2.0",
    "id": "...",
    "error": {
        "code": -32000,
        "message": "failed with xxx gas: insufficient funds for gas * price + value: address 0x... have xxx want xxx"
    }
}
```

The data returned by the function is `undefined` as `response.result` does not exist.
```
    const response = await res.json();
    return response.result;
```

### Expected behavior

Be able to catch or access the error.

```
    const response = await res.json();
    if (response.error) throw response.error;
    return response.result;
```

### Version

4.0.4

**Comment by bangtoven** [comment]
thanks for the report. will address this in following version
