### ISSUE TITLE
Bug: signing message on iOS Safari is not working if there is a delay

### ISSUE THREAD

**Issue by magiziz** [coinbase/coinbase-wallet-sdk#1440]
### Describe the bug

I recently used latest wagmi version and noticed that if there is a delay before you sign a message with passkey you'll get "Pop up window failed to open" error message

### Steps

1. Install latest Wagmi version 2.12.25 and add [coinbaseWallet](https://wagmi.sh/react/api/connectors/coinbaseWallet#coinbasewallet) connector
2. Add a sign message button (the message can be anything)
3. Add a click function to the sign message button that has a 5 second timer before signing the message. You can simply create a `sleep` function that will act as a timer.
4. You'll see the `"Pop up window failed to open"` error in the console

### Expected behavior

It shouldn't throw an error. I believe there is some browser policy in iOS Safari that prevents the window popup from being opened up if there is a delay, but not quite sure. I caught this bug when trying to implement Sign-in with ethereum which required a few asynchronous steps before signing a message.

### Version

4.1.0

### Smartphone

- iPhone 14 - iOS 17.6.1

**Comment by cb-jake** [comment]
@magiziz Thanks for flagging. We will take a look into the issue and report back.

**Comment by cb-jake** [comment]
@magiziz Do you have any async events happening between the CTA and the call that opens the pop?

**Comment by magiziz** [comment]
> @magiziz Do you have any async events happening between the CTA and the call that opens the pop? From what I understand this is an issue with iOS and how they process window.open events. 

Yes we have asynchronous events happening before opening the popup.

In our case we're fetching nonce when using Sign-in with ethereum. Is there a possible fix for this that can be done in the SDK level ? I believe this affects all users 🤔

**Comment by cb-jake** [comment]
My understanding of the issue is this happens at the system level (ios, etc..). We could potentially popup a toast from the SDK asking users to click again if a popup blocker is detected but thats not an ideal UX either. We do have this documented here https://www.smartwallet.dev/guides/tips/popup-tips#default-blocking-behavior.

Is it possible to prefetch the nonce, prior to users clicking "connect"?

**Comment by magiziz** [comment]
@cb-jake Yeah i think it's possible to do some type of prefetching if there is no solution around it. I'll close this issue for now, thanks for the help 🙏

**Comment by cb-jake** [comment]
Thanks @magiziz We're exploring some other solutions that would resolve this, but they're still in ideation phase and we dont have a timeline on them quite yet. I'll re-visit here when we have an update.

**Comment by dropkick1325** [comment]
Okay thank u
