### ISSUE TITLE
Bug: Can't import the named export 'hashForSignTypedDataLegacy' (imported as 'eip712') from default-exporting module

### ISSUE THREAD

**Issue by shayesteMalekpour** [coinbase/coinbase-wallet-sdk#1448]
### Describe the bug

Can't import the named export 'hashForSignTypedDataLegacy' (imported as 'eip712') from default-exporting module

### Steps

i'm using wagmi and npw my project is failed due to this update in Coinbase

### Expected behavior

it makes the build fails

**Comment by cb-jake** [comment]
Hi @shayesteMalekpour, thanks for flagging. What version of the SDK are you using?

**Comment by cb-jake** [comment]
@shayesteMalekpour please update to the most recent version of the SDK and let us know if you're still facing the same issue.  If yes please provide additional info about the app you're building. Thanks

**Comment by cb-jake** [comment]
Going to close this issue. It should be resolved by bumping to the latest version. If you're still running into this issue, please feel free to reopen it. Thanks!
