### ISSUE TITLE
Sometimes It says Link failed in wallet app, but event is received in webapp & QR modal is closed

### ISSUE THREAD

**Issue by aksdevac** [coinbase/coinbase-wallet-sdk#159]
Sometimes if previously connected wallet is connected again (after killing coinbase mobile app & opening again or fresh connect) by scanning QR. accounts response is not received only `"type":"Linked"` event is received 
& it works (Web3Response is received) if requestAccounts is called again.

it seems there is some communication  issue with coinbase app & relay server api.

**Comment by ravisriv** [comment]
This is a serious issue from the point of view of Coinbase wallet user experience.

**Comment by aksdevac** [comment]
it seems that with version `2.1.9` it is working in much better way, now it has only one minor issue, sometimes it says link failed in coinbase wallet app, but callback is received in webapp, & it works again only after reset clicking connection from webapp confirm on phone popup & rescanning the QR code.

**Comment by ravenvn** [comment]
@aksdevac could u share me the code to connect coinbase wallet using wallet link? I couldn't make it work.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
