### ISSUE TITLE
Support for EIP712 Arrays in typedData

### ISSUE THREAD

**Issue by samuveth** [coinbase/coinbase-wallet-sdk#196]
Currently walletlink (Coinbase Wallet) doesn't seem to support signing messages with Arrays in typedData. At Snapshot we are planning to switch fully to EIP712 and require this for some voting types and for creating proposals.

**Comment by bonustrack** [comment]
You can use this proposal to test signing a message with array type: https://bafybeial75q5u2edo3gg5w7z5bkp3id6pgpr4hghebulfowfx74rak2vty.on.fleek.co/#/fabien.eth/proposal/0x1dbca6fa6e9685180dfa2b2bcd10bbb51721c16a1135fdbb40f904747c09bdb5

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
