### ISSUE TITLE
Passing wrong default chainId in makeWeb3Provider puts provider in corrupt state

### ISSUE THREAD

**Issue by btraut** [coinbase/coinbase-wallet-sdk#225]
It's possible I've misunderstood documentation, but I've scoured as many examples as I can and I can't seem to figure out how to resolve this issue:

My dapp connects to walletlink without any special config:

```
        const walletLink = new WalletLink({ … });
        this._provider = walletLink.makeWeb3Provider(INFURA_API_KEY);
```

The d.ts file states that the default second param to `makeWeb3Provider` (the `chainId`) is 1. I'm confused by this param because I have no idea what chain the user would like to connect to, and if it's not mainnet, it can cause issues. Here's an example flow:

1. User opens Coinbase Wallet on his phone and chooses Kovan as his "Default Network".
2. On opens the dapp, clicks to connect Coinbase Wallet. QR code is shown.
3. User scans QR code to connect.

At this point, the dapp connects the user and correctly identifies that the user wants Kovan (42). walletlink automatically sets "DefaultChainId = 42" in local storage. The dapp is able to check balances and execute transactions on the Kovan network. Until…

4. User refreshes the page on the dapp. The dapp reconnects as per the code above, passing no `chainId`.

Now the dapp appears connected and still reports Kovan as its network, because walletlink internally checks local storage to report network, but it's a lie. When attempting to make any requests or execute any contracts, the provider uses whatever network was passed to `makeWeb3Provider`, or in my case, the default which is mainnet. The provider is corrupted.

To temporarily resolve the issue, I've used the following hack to detect the user's last chainId and pass it as the default chainId:

```
      let defaultChainId = 1;
      try {
        const storage = window.localStorage.getItem(
          '-walletlink:https://www.walletlink.org:DefaultChainId'
        );
        if (storage) {
          defaultChainId = Number(storage);
        }
      } catch (error) {
        console.warn(
          `Couldn't connect to local storage to find walletconnect's default chain id.`
        );
      }
```

It seems there's a few possible solutions y'all could use internally:

1. Have the `WalletLinkProvider` constructor check for the network storage's default if no chainId is passed. This would essentially take my code above and move it into the `WalletLinkProvider`.
2. Likely better because it avoids stale state: don't ask developers to provide a default `chainId` and don't assume any defaults; always check the wallet's current network.

Thanks!

**Comment by btraut** [comment]
Hmm, perhaps I've resolved this on my own. I failed to consider that I was passing the mainnet infura URL to the WalletLink constructor and then passing a Kovan chainId to `makeWeb3Provider`.

Needless to say, I've found this API very confusing.

**Comment by Pornprasert** [comment]
> It's possible I've misunderstood documentation, but I've scoured as many examples as I can and I can't seem to figure out how to resolve this issue:
> 
> 
> 
> My dapp connects to walletlink without any special config:
> 
> 
> 
> ```
> 
>         const walletLink = new WalletLink({ … });
> 
>         this._provider = walletLink.makeWeb3Provider(INFURA_API_KEY);
> 
> ```
> 
> 
> 
> The d.ts file states that the default second param to `makeWeb3Provider` (the `chainId`) is 1. I'm confused by this param because I have no idea what chain the user would like to connect to, and if it's not mainnet, it can cause issues. Here's an example flow:
> 
> 
> 
> 1. User opens Coinbase Wallet on his phone and chooses Kovan as his "Default Network".
> 
> 2. On opens the dapp, clicks to connect Coinbase Wallet. QR code is shown.
> 
> 3. User scans QR code to connect.
> 
> 
> 
> At this point, the dapp connects the user and correctly identifies that the user wants Kovan (42). walletlink automatically sets "DefaultChainId = 42" in local storage. The dapp is able to check balances and execute transactions on the Kovan network. Until…
> 
> 
> 
> 4. User refreshes the page on the dapp. The dapp reconnects as per the code above, passing no `chainId`.
> 
> 
> 
> Now the dapp appears connected and still reports Kovan as its network, because walletlink internally checks local storage to report network, but it's a lie. When attempting to make any requests or execute any contracts, the provider uses whatever network was passed to `makeWeb3Provider`, or in my case, the default which is mainnet. The provider is corrupted.
> 
> 
> 
> To temporarily resolve the issue, I've used the following hack to detect the user's last chainId and pass it as the default chainId:
> 
> 
> 
> ```
> 
>       let defaultChainId = 1;
> 
>       try {
> 
>         const storage = window.localStorage.getItem(
> 
>           '-walletlink:https://www.walletlink.org:DefaultChainId'
> 
>         );
> 
>         if (storage) {
> 
>           defaultChainId = Number(storage);
> 
>         }
> 
>       } catch (error) {
> 
>         console.warn(
> 
>           `Couldn't connect to local storage to find walletconnect's default chain id.`
> 
>         );
> 
>       }
> 
> ```
> 
> 
> 
> It seems there's a few possible solutions y'all could use internally:
> 
> 
> 
> 1. Have the `WalletLinkProvider` constructor check for the network storage's default if no chainId is passed. This would essentially take my code above and move it into the `WalletLinkProvider`.
> 
> 2. Likely better because it avoids stale state: don't ask developers to provide a default `chainId` and don't assume any defaults; always check the wallet's current network.
> 
> 
> 
> Thanks!

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
