### ISSUE TITLE
Walletlink not working on mobile

### ISSUE THREAD

**Issue by LukeSamkharadze** [coinbase/coinbase-wallet-sdk#231]
This code perfectly works on chrome with coinbase extention instaled, but doesn't work in trust wallet browser on mobile

```JS
  const walletLink = new WalletLink({
    appName: "TEST TEST",
    appLogoUrl: "https://random-picture.com",
    darkMode: true,
  });

  ethereum = walletLink.makeWeb3Provider("https://bsc-dataseed1.binance.org/", 56);
  web3 = new Web3(ethereum);
  account = await ethereum
    .send("eth_requestAccounts")
    .then((o) => o[0]);
```

`account` is undefined on mobile while using coinbase extension

![image](https://user-images.githubusercontent.com/31849767/144579430-08d4c23f-b590-43ce-adc5-495a8154efee.jpeg)

![image](https://user-images.githubusercontent.com/31849767/144579488-d637f3a5-8636-4157-bf90-bbd8575c1003.jpeg)

'[object Object]' should be wallet address. It should behave same as on PC.

**Comment by LukeSamkharadze** [comment]
On mobile:

![image](https://user-images.githubusercontent.com/31849767/144579430-08d4c23f-b590-43ce-adc5-495a8154efee.jpeg)

![image](https://user-images.githubusercontent.com/31849767/144579488-d637f3a5-8636-4157-bf90-bbd8575c1003.jpeg)

'object object' should be wallet address. It should behave same as on PC.

**Comment by mattmcguin** [comment]
Experiencing this as well

**Comment by LukeSamkharadze** [comment]
@mattmcguin 

Used this snippet to fix the issue, apperently on mobile accounts are in `result` array, but I think issue still should be opened

```JS
  account = await ethereum
    .send("eth_requestAccounts")
    .then((o) => o[0] || o.result[0]);
```

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
