### ISSUE TITLE
CDN vanilla JS import instead of NPM

### ISSUE THREAD

**Issue by xpluscal** [coinbase/coinbase-wallet-sdk#235]
is there an option to import Walletlink other than via NPM?

**Comment by Bavragor** [comment]
Had the same question and actually found a solution: https://www.skypack.dev/view/walletlink

**Comment by IceCodeProductions** [comment]
I have created a project that allows you to convert the WalletLink into a pure javascript file and you can host this on your own website or cdn

https://github.com/IceCodeProductions/Javascript-WalletLink

**Comment by ljharb** [comment]
You can convert it yourself with a bundler; I highly suggest not trusting a third party for an SDK that deals with money.

There is not currently an official option to use almost every JS library outside of npm. What's the use case for avoiding npm?

**Comment by IceCodeProductions** [comment]
The project requires the use of NPM.  This is for those that want to create a pure javascript version of coinbaseWalletSDK without using node.  This does nothing more than creates a bundle package to host the javascript.  If this is wrong, then I can remove my project.

**Comment by ljharb** [comment]
@IceCodeProductions i didn't mean to imply you personally, or your project, were a concern - just that _in general_ one should only use software via official distribution channels.

I'm not sure why anyone would be using any javascript anywhere without using node (or the equivalent) - as a linter, a testing tool, a build tool, etc, let alone as a package management tool.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
