### ISSUE TITLE
Support for mobile apps

### ISSUE THREAD

**Issue by dokocat** [coinbase/coinbase-wallet-sdk#237]
Hi! Is there any plans to support mobile apps wanting to connect users wallets to their app via Coinbase? Similar to how Opensea is using Metamask and Trustwallet for login on mobile.

**Comment by dokocat** [comment]
Any update on this?

**Comment by vishnumad** [comment]
Support for mobile apps is available through our mobile wallet protocol
https://github.com/coinbase/wallet-mobile-sdk
