### ISSUE TITLE
Unhandled Rejection (Error): User denied account authorization

### ISSUE THREAD

**Issue by fsobh** [coinbase/coinbase-wallet-sdk#241]
Getting this error when a user dismisses the Coinbase modal

**Comment by kyokosdream** [comment]
Not sure why you refer to this as an error, if you dismiss authorizing the `eth_getAccounts` method an error will be thrown. I don't believe this is an error and this issue should be closed by the repo maintainers.

**Comment by ljharb** [comment]
Either way, we need more info to reproduce.
