### ISSUE TITLE
e2e test API?

### ISSUE THREAD

**Issue by ivelin** [coinbase/coinbase-wallet-sdk#256]
Is there a plan for WalletLink to provide a standardized API for e2e testing interactions between web3 apps and crypto wallets? 

Dappeteer and Synpress provide e2e API for MetaMask and Chrome, but they are brittle because they 'screen scrape' the MetaMask HTML code, which changes from version to version.

A standardized cross wallet e2e testing API would be helpful for the web3 ecosystem.

Thank you!

**Comment by bangtoven** [comment]
hi. sorry for the belated response. 
we are marking old issues closed for now.
for e2e testing, here's a library you may try to integrate with cbwallet. 
https://github.com/TenKeyLabs/dappwright/tree/coinbase-demo
