### ISSUE TITLE
WalletLink connection inside iframe is blocked on Safari

### ISSUE THREAD

**Issue by RuggeroCino** [coinbase/coinbase-wallet-sdk#258]
When trying to connect to WalletLink from an iframe, the universal link used to redirect to the WalletLink app is blocked and the following waning is thrown by Safari:

```
Error: The page at https://[...] was not allowed to display insecure content from itms-appss://apps.apple.com/app/id1278383455.
```

I suspect that this is caused by the redirect in the following line:
https://github.com/walletlink/walletlink/blob/6da899882348e7bdcb75840d8a0dd088fd0e8d71/js/src/relay/WalletLinkRelay.ts#L571

Would it make sense to use `window.top.location` (see [SO topic](https://stackoverflow.com/questions/580669/redirect-parent-window-from-an-iframe-action)) instead to make the WalletLink connection work also when used inside an iframe? Something like the following:
```
window.top.location.href = `https://go.cb-w.com/xoXnYwQimhb?cb_url=${window.top.location.href}
```
This would also open the Coinbase browser showing the website which is using the iframe instead of showing the iframe itself.

**Comment by lucianogreiner** [comment]
Same here on Chrome. Using Walletlink along with Web3modal in an iframe. Looks like the provider.send('eth_requestAccounts') function never gets resolved if on an iframe. Thoughts?
