### ISSUE TITLE
Uncaught TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.

### ISSUE THREAD

**Issue by Zavtramen** [coinbase/coinbase-wallet-sdk#267]
I'm trying to add WalletLink support to Nuxt+Vue (2.x) application. Doing everything from readme.md but, got the error (this one from WalletLink 2.2.6 version):
![image](https://user-images.githubusercontent.com/20144339/149123299-be13eaac-7a0c-41d5-83b2-8485910d240c.png)
Error is thrown from the very beginning, in the "new WalletLink" part.
Was trying different versions: 2.0.1, 2.2.6, 2.4.2 - all the same.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
