### ISSUE TITLE
WebSocket connection to 'wss://www.walletlink.org/rpc' failed: 

### ISSUE THREAD

**Issue by 1997roylee** [coinbase/coinbase-wallet-sdk#318]
![螢幕截圖 2022-02-10 上午12 52 20](https://user-images.githubusercontent.com/53046899/153249605-1fff4b37-283c-4a3a-8282-45faeb69803f.png)

I have no idea how to solve this problem and it drive me feel crazy.

**Comment by ewerx** [comment]
Could you provide some more context on how you encounter this state?

**Comment by 1997roylee** [comment]
First, I sent a "eth_requestAccounts" request method to coinbase and I click the cancel button to reject this request and redirect to my page, this bug occurs.

**Comment by aiekseu** [comment]
@1997roylee for me the problem was in CORS policy – temporary allowing all origins solves the issue

**Comment by sjc5** [comment]
Ran across this today via RainbowKit. Seemed random. Fully clearing localhost:3000 browser cache / storage fixed it in case anyone else runs across this.
