### ISSUE TITLE
Requests to Mumbai RPC return with 403 error

### ISSUE THREAD

**Issue by fzavalia** [coinbase/coinbase-wallet-sdk#324]
While connecting my coinbase wallet via the sdk to the mumbai network directly, all calls to the rpc `https://polygon-mumbai-infura.wallet.coinbase.com` fail with a 403 error. 

```
Request URL: https://polygon-mumbai-infura.wallet.coinbase.com/
Request Method: POST
Status Code: 403 
Remote Address: 104.18.20.159:443
Referrer Policy: strict-origin-when-cross-origin
```

Response:

```
{
  "jsonrpc": "2.0",
  "id": 72,
  "error": {
    "code": -32600,
    "message": "project ID is required",
    "data": {
      "reason": "project ID not provided",
      "see": "https://infura.io/dashboard"
    }
  }
}
```

I'm providing another `rpcUrl` than the one that is failing and according to the README.

"Walletlink uses an rpcUrl provided by Coinbase Wallet clients regardless of the rpcUrl passed into makeWeb3Provider for whitelisted networks. Walletlink needs an rpcUrl to be provided by the dapp as a fallback."

I would have though that when coinbase's rpcs fail, the one I provide would be used.

Tell me if you need any more info, I'm only having issues when connecting directly to mumbai.

**Comment by fzavalia** [comment]
I'm using the sdk via https://www.npmjs.com/package/@web3-react/walletlink-connector which currently installs the latest version of this package (v2.4.7)

Would have created an issue on that project but due to the nature of the error, this seems to be the correct place.

**Comment by ewerx** [comment]
Thanks for the report. We are investigating these two issues 1) 403 error from the internal rpc endpoint and 2) fallback rpc endpoint not used on 403 error.

**Comment by Fivehundredth** [comment]
Can confirm, having the same issue. Walletlink doesnt fallback to provided PRC url.

**Comment by nachomazzara** [comment]
Hey folks, do you have any update on this?

**Comment by bangtoven** [comment]
hello folks 👋 
1. we are investigating why our proxy is returning 403 for requests to polygon mumbai. 
2. re fallback rpc url, can you try linking your phone directly without chrome extension? cc @hieronymus777

**Comment by joaquim-verges** [comment]
seeing the same issue linking via phone directly - all mumbai transactions fail.

**Comment by mikehunter1990** [comment]
How

**Comment by ewerx** [comment]
A backend fix was deployed to address the 403 error, please confirm if this is resolved for you.

**Comment by fzavalia** [comment]
I can now send transactions on mumbai, 403 error is no happening anymore 😁
