### ISSUE TITLE
[feature request] open source the server spec and allow custom server implementations

### ISSUE THREAD

**Issue by brendanjryan** [coinbase/coinbase-wallet-sdk#330]
Hello! 

Is there any interest on the part of the Coinbase team to open source an example implementation of the WalletLink server or at least provide an implementation spec? This can _somewhat_ be derived form the server/client messages [0] but is not readily evident.

I believe that this would further increase adoption and would benefit this project by:

1. Improving security: By allowing large users to "bring their own server" with their own security controls.
2. Increasing transparency: By allowing app developers / users to easily grok the security behind this critical protocol. See prior art for WalletConnect [0].
3. Foster innovation: Allowing other companies and individuals to contribute back to the server spec (count me in here!) 

[0] https://github.com/coinbase/coinbase-wallet-sdk/tree/master/src/connection
[1] https://docs.walletconnect.com/bridge-server

**Comment by brendanww** [comment]
@brendanjryan you can browse the server code here -> https://github.com/coinbase/coinbase-wallet-sdk/tree/f1de7016fa471514c8de979c421a30fd2ae8b5a5/server

And the protocol is designed such that you can swap in any server implementation via the `WALLETLINK_URL` environment variable when building walletlink

**Comment by brendanjryan** [comment]
ack thanks for the flag @brendanww ! 

In this case I was specifically interested in seeing if there was interest in an open spec / reference implementation beyond what is in that package. If so, I would be happy to donate on as well!

**Comment by ewerx** [comment]
Yes, an open spec and reference implementation of the server is something we're interested in providing. I don't have any details to share now but I will leave this thread open to share updates and continue the discussion. Thanks for making the case for this addition.
