### ISSUE TITLE
I am trying to import wallet seed but activity indicator keeps spinning.

### ISSUE THREAD

**Issue by kcmed420** [coinbase/coinbase-wallet-sdk#342]
I am trying to import wallet seed but activity indicator keeps spinning.

__Originally posted by @rocxteady in https://github.com/petejkim/metamask-mobile/payme__

**Comment by Bleujj1** [comment]
You will need to synchronize your wallet and debug it with bech13

**Comment by ewerx** [comment]
This does not sound like an SDK issue. You can get help for Coinbase Wallet [here](https://help.coinbase.com/en/wallet).

**Comment by kcmed420** [comment]
> I am trying to import wallet seed but activity indicator keeps spinning.
- [ ] > 
> __Originally posted by @Roxy ready in https://github.com/Peter Kim/meta mask -mobile/payme__
