### ISSUE TITLE
wallet_watchAsset does not exist/is not available

### ISSUE THREAD

**Issue by ccosmincc** [coinbase/coinbase-wallet-sdk#379]
I am trying to track a specific token following the steps provided [here](https://github.com/coinbase/coinbase-wallet-sdk#suggest-client-wallet-track-a-specific-token-with-eip-747), but I always get the following response:
`{
    "jsonrpc":"2.0","id":6,
    "error":{"code":-32601,"message":"the method wallet_watchAsset does not exist/is not available"}
}`
This is the request that is being made (I'm using the same token as in the example):
`{
     "method":"wallet_watchAsset",
     "params":[{
           "type":"ERC20",
           "options":{
                  "address":"0xcf664087a5bb0237a0bad6742852ec6c8d69a27a",
                  "symbol":"WONE",
                  "decimals":18,
                  "image":"https://s2.coinmarketcap.com/static/img/coins/64x64/11696.png"
             }
     }],
     "jsonrpc":"2.0",
     "id":6
}`
I got the same result on all networks that I tried:
Ethereum mainnet ( https://mainnet-infura.wallet.coinbase.com/ )
Ethereum Ropsten ( https://ropsten-infura.wallet.coinbase.com/ )
Binance Smart Chain Testnet ( https://data-seed-prebsc-1-s1.binance.org:8545/ )

Also, sending the params parameter as object, not as array, does not seem to work for Ethereum mainnet and Ethereum Ropsten, returning `{"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid json request"}}`

SDK version: 3.0.1 (reproducible also on v2.4.4)
Browser: Chrome

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and make sure you debug it with bech13.

**Comment by ccosmincc** [comment]
@Yuxanju could you be more specific? What do you mean by "synchronize your wallet" and what is "bech13"? If by "synchronize wallet" you mean the process described [here](https://github.com/coinbase/coinbase-wallet-sdk#initializing-wallet-sdk-and-a-wallet-sdk-powered-web3-object), I already did that. I was also able to switch/add networks as described [here](https://github.com/coinbase/coinbase-wallet-sdk#switching--adding-alternative-evm-compatible-chains), it's just the `wallet_watchAsset` example that does not work.

**Comment by Yuxanju** [comment]
By synchronizing your wallet_watchAsset will work .. I can send you the
link that will guide you to where you will click synchronize wallet and
then you click on that and you reboot your device

**Comment by ccosmincc** [comment]
@Yuxanju secret links, rebooting devices (I'm in a browser context), sounds "great". Should I maybe just give you my private key and you can do that for me, please? :)
Anybody else having a more realistic idea about the cause of this issue?

**Comment by mikehunter1990** [comment]
How

**Comment by Yuxanju** [comment]
Why would you give me your private key.. I don’t need that .. I’m only
trying to help you .. it’s an ellipal secure encrypted link meant for
synchronizing and debugging

**Comment by mikehunter1990** [comment]
How

**Comment by mikehunter1990** [comment]
Y

**Comment by Yuxanju** [comment]
You will have to use the ellipal encrypted secure site . You follow the
site till you get to synchronize wallet and then you click on it
www.ellipalsuites.com

**Comment by ccosmincc** [comment]
@Yuxanju I might be missing something (although I doubt it), but to me the whole issue revolves around the POST request that is being sent to one of the URLs from my first comment (based on the selectec network) and the failed response that the server returns. I can see it all in the Network tab of the browser's dev tools. Not sure what else is left for me to debug/synchronize, it seems like a server-side problem.

**Comment by Yuxanju** [comment]
Just follow the url I sent to you and make sure you debug it

**Comment by Yuxanju** [comment]
Have you follow the url?

**Comment by jeongmincho** [comment]
`wallet_watchAsset` was added to Coinbase Wallet after this issue was raised. there should be no issues with calling the JSON RPC method now, please raise another issue if otherwise

**Comment by ccosmincc** [comment]
@jeongmincho now I get a different error when trying to call the same method with the same parameters as in the first comment. Below is the relevant stack trace: 
![image](https://user-images.githubusercontent.com/24733506/174627699-a48d4c0e-1d2b-4515-869c-1395be7fb724.png)

**Comment by raiiih** [comment]
wallet_watchAsset
Someone is using my wallet
