### ISSUE TITLE
Google tag manager: ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by pi0neerpat** [coinbase/coinbase-wallet-sdk#38]
Getting this ugly error message, any time I call `new WalletLink` . Note the tag shown here is obscured for my sake.

`GET https://www.googletagmanager.com/gtag/js?id=UA-1*******net::ERR_NAME_NOT_RESOLVED`
> Referrer Policy: no-referrer-when-downgrade

While we are on the topic, I urge you to consider removing Google completely from this library.  It's not in the ethos of the community to be using Google to track users. There are plenty of open source tools for analytics available. Personally I use https://matomo.org and it rocks!

**Comment by herewegoagain2** [comment]
> Getting this ugly error message, any time I call `new WalletLink` . Note the tag shown here is obscured for my sake.
> 
> 
> 
> `GET https://www.googletagmanager.com/gtag/js?id=UA-1*******net::ERR_NAME_NOT_RESOLVED`
> 
> > Referrer Policy: no-referrer-when-downgrade
> 
> 
> 
> While we are on the topic, I urge you to consider removing Google completely from this library.  It's not in the ethos of the community to be using Google to track users. There are plenty of open source tools for analytics available. Personally I use https://matomo.org and it rocks!

**Comment by herewegoagain2** [comment]
> Getting this ugly error message, any time I call `new WalletLink` . Note the tag shown here is obscured for my sake.
> 
> 
> 
> `GET https://www.googletagmanager.com/gtag/js?id=UA-1*******net::ERR_NAME_NOT_RESOLVED`
> 
> > Referrer Policy: no-referrer-when-downgrade
> 
> 
> 
> While we are on the topic, I urge you to consider removing Google completely from this library.  It's not in the ethos of the community to be using Google to track users. There are plenty of open source tools for analytics available. Personally I use https://matomo.org and it rocks!

- []()

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please open a new one if needed. thanks.
