### ISSUE TITLE
Fraudulent behavior through Pig-butchering plate. Please fix this.

### ISSUE THREAD

**Issue by alonsoir** [coinbase/coinbase-wallet-sdk#380]
Why is it allowed to connect fraudulent websites in the coinbase wallet app? that is, there are hundreds of thousands of people who are being or have been scammed using the pig-butchering mechanism in which a person is made to connect to a website through the bottom middle button in Coinbase Wallet that allows them to create a contract on the blockchain that drains all funds from that wallet.

Are the developers aware of the damage that this feature they offer is causing hundreds of thousands of people in the world? Do your bosses tell you?

I believe that there are many ways to combat this scourge.
There is a list that is updated every day with these fraudulent websites, since there is that button, why not control these websites? something as simple as if said website appears on the blacklist, warn the wallet user.

Also, why does no email of any kind reach the user of the wallet that said contract has been written in the blockchain? Why is it not noticed that this operation is going to be carried out? This type of operation could be put on hold for a couple of days, or the operation could only be activated once the user receives the contract that is intended to be written in the blockchain by email, asking the wallet user Password. You should simply capture said request, create a process in which the information is collected, translate it so that anyone understands that you want to make said contract, send it by email to the client of the wallet, your clients and then they with better information decide if they really want to create such a contract.

I don't know if this is already being dealt with in a user story, or in a previously created issue.

I hope you can help users because I think they are not aware of the pain that the state of the current implementation of Coinbase Wallet has caused.

**Comment by alonsoir** [comment]
Hi? is anybody going to ask me what the problem is? Does someone from the development team want to be interested in a problem that is badly affecting thousands of users of this app?

**Comment by ewerx** [comment]
[Coinbase Wallet](https://www.coinbase.com/wallet) is a self-custody wallet and does not collect user contact information (unlike Coinbase the exchange). Being a self-custody wallet, it interacts directly with the blockchain networks and dapps and there are no centralized mechanisms to intercept requests and contact users as you suggest. However, we are actively working on mechanisms to help combat scam and warn users about interacting with scam tokens and contracts in Wallet. 

This GitHub project is for the Coinbase Wallet SDK only. For inquiries about the Coinbase Wallet please [contact support](https://help.coinbase.com/en/contact-us).

**Comment by alonsoir** [comment]
Hello, with respect, but you can and should do much more. What if you check on the client or the server the plausibility of whether a third-party Defi app is trustworthy or not? all you have to do is cache said list in the server space and ask a question from the app. It doesn't even take five minutes to maintain something like this.

There is a list maintained by victims of this type of scam who have used your software. Nor are they going to ask what the list is? do not want to give more work? where are your professional ethics when it comes to trying to create the best and safest product possible for your customers? Are they aware of the pain and loss of human lives that their actions have allowed?
  
Are you so decentralized that not even a simple REST request can you make to your servers?

How is it possible that said app has been able to create said fraudulent contract and at no time have you notified me?

**Comment by janinewhite** [comment]
> [Coinbase Wallet](https://www.coinbase.com/wallet) is a self-custody wallet and does not collect user contact information (unlike Coinbase the exchange). Being a self-custody wallet, it interacts directly with the blockchain networks and dapps and there are no centralized mechanisms to intercept requests and contact users as you suggest. However, we are actively working on mechanisms to help combat scam and warn users about interacting with scam tokens and contracts in Wallet.
> 
> This GitHub project is for the Coinbase Wallet SDK only. For inquiries about the Coinbase Wallet please [contact support](https://help.coinbase.com/en/contact-us).

You could ask people to enter their email address in the settings, so there's no need to centralize contact information, then maintain a list of scam websites that you read and warn people about. It can be done for Web2 browsers, why not Web3? This request is very feasible.
