### ISSUE TITLE
Support for mobile deep linking 

### ISSUE THREAD

**Issue by pi0neerpat** [coinbase/coinbase-wallet-sdk#40]
### Issue

The current implementation requires two devices- desktop and mobile. The only alternative is to use the built-in browser in the Coinbase Wallet. This creates a bad user experience for these reasons:

- User is much more likely to navigate to a dapp from their default mobile browser, not from the Coinbase Wallet browser. Having to copy/paste a URL into Coinbase Wallet browser is not a good experience.
- Progressive Web Apps are not possible, since a dapp can only be opened in Coinbase Wallet browser.

### Potential solution

Support should be added for deep linking / universal linking 

- If desktop, show the standard QR prompt
- If mobile, show a button to open Coinbase Wallet using deep linking

WalletConnect has already implemented this feature (see screenshot below). Their documentation only includes mobile linking for native apps. However it works for browser-based apps as well, which is what I am suggesting here.

![Screenshot_20200708-122356](https://user-images.githubusercontent.com/35622595/86948526-412d7f80-c11b-11ea-8d07-a91ddffda5ee.png)

### Discussion

1. Adding this feature will likely mean less users in the Coinbase Wallet browser initially, but it doesn't necessarily mean they won't use the browser at all, eg. to discover new apps. Despite this, it doesn't appear you are doing any sponsored promotions in the browser. Therefore, I don't think that this will have any financial impact on the company. However this isn't for me to decide.

2. Progressive Web Apps are extremely important for dapp developers. They are the only "safe space" we have for delivering native-like experiences. In my opinion, its not worth the effort to build for Google and Apple stores, given harsh treatment against crypto apps (even reputable ones like MetaMask). Forcing users to use the built-in wallet browser is a slap in the face for dapp developers.

**Comment by sid-toshi** [comment]
Hi Pat, thanks for the feedback! This is a great idea. While we work on it, we already do have support for mobile deeplinking on Coinbase Wallet. You can create one in Wallet's dapp browser by navigating to the dapp and then tapping the overflow menu and tapping share. Feel free to use that in the interim while we work on a more integrated mobile deeplinking solution for WalletLink.

**Comment by pi0neerpat** [comment]
@sid-toshi I was unable to create a permanent reusable deeplink in Wallet's dapp browser. Should I make a new issue?

I also tried making my own deeplinks:

- `ethereum:spendless.io/login` : opens app but doesn't switch to browser
- `coinbase:spendless.io/login`: Nothing happens / no app registered
- `toshi:spendless.io/login`: Nothing happens / no app registered

It's strange because https://github.com/LinkdropHQ/linkdrop-monorepo/blob/a4bb0caebfbf7aa0fe4eedebfc48cf5919034503/packages/apps/app-claim/components/pages/main/wallet-choose-page/index.js#L55 uses the "coinbase" one

**Comment by cortesa** [comment]
Hi, @sid-toshi ,

How can I go to Wallet`s dapp browser?
I'm looking for a way to open de mobile app instead the QR, it is quite difficult to scan the QR on the same mobile ;)
thanks

**Comment by sid-toshi** [comment]
Hi @cortesa you're totally right. We're working on automatically showing deeplinks on mobile web for WalletLink. Until then, you can create a deeplink to your site manually (just open your site in Wallet's dapp browser, click the three-dot menu, and Share to generate a deeplink). That deeplink will take users from mobile web directly into the dapp browser and load your dapp. If the user doesn't have Wallet it will take them to an install. When on mobile web, instead of showing WalletLink's QR code, you can just serve the deeplink instead. Let me know if that works.

**Comment by cortesa** [comment]
omw, I'll give you my feedback, thanks

**Comment by cortesa** [comment]
it works although it doesn't fit the expected UX, I'll try to propose a flow using this in-browser way, any ETA for this feature?

**Comment by sid-toshi** [comment]
We're planning to get the automatic deeplink feature built this quarter, but tough to promise an exact date. Do you mind sharing screenshots of the mobile flow with me on Twitter DMs? @sid_coelho. I can see if there's any other quick fixes.

**Comment by coin77** [comment]
Any news on this issue?

**Comment by cortesa** [comment]
Hi, thanks for the following, I and my mates are waiting for the update, meanwhile we've disabled the option due bad UX.

Any update is welcome, we really appreciate your effort to keep this lib in its high quality level

Thanks
Andres Cortes (cortesa)

**Comment by cortesa** [comment]
Hi, guys, is there any update for this Issue?

**Comment by dparker2** [comment]
The dApp I’m building requires inline video playback and does not work properly in Coinbase wallet’s in-app browser, but it does works in Safari and Chrome. Deep linking directly to the app does not work for this. Please either add support for walletconnect to cb wallet, or add this feature to walletlink

**Comment by bangtoven** [comment]
hi. sorry for the belated response. 
closing this issue as cbwallet sdk now supports deeplinking on mobile environment.

@dparker2 can you open a new issue about your use case around video on regular browsers please?
