### ISSUE TITLE
"Install Extension" link is broken

### ISSUE THREAD

**Issue by btraut** [coinbase/coinbase-wallet-sdk#407]
On my dapp, the `@coinbase/wallet-sdk` works great when paired with the mobile app via QR code, but it has an issue with the browser extension -- When I click to connect my Coinbase Wallet on a browser that doesn't have the extension installed, a "Install Extension" button is shown, and this button sends me to a dead link: https://api.wallet.coinbase.com/rpc/v2/desktop/chrome.

**Comment by erin-at-work** [comment]
Thanks @btraut for raising this! We've now resolved this issue.
Link should now properly redirect to the chrome extension link
