### ISSUE TITLE
Android: embedded browser (webview) does not handle deeplinks/universal links

### ISSUE THREAD

**Issue by jamiely** [coinbase/coinbase-wallet-sdk#421]
**Describe the bug**

On Android, the embedded browser does NOT open deep/universal links appropriately. 

**To Reproduce**

0. Setup your device with the Youtube app installed
1. Open this on Android: https://go.cb-w.com/xoXnYwQimhb?cb_url=https%3A%2F%2Frevolvingantiqueexecutables.jamiely3.repl.co%2F (alternatively, open the Coinbase Wallet embedded browser and enter https://revolvingantiqueexecutables.jamiely3.repl.co/). This page is just a simple HTML page that has a youtube link in it (https://replit.com/@JamieLy3/RevolvingAntiqueExecutables#index.html).
2. Click on "Youtube Universal Link"
3. The page should open in Youtube, but it opens in the browser instead

**Expected behavior**
The link should open in the Youtube app (see this Stackoverflow post for implementation https://stackoverflow.com/questions/25672330/how-to-enable-deep-linking-in-webview-on-android-app). For example, opening https://revolvingantiqueexecutables.jamiely3.repl.co in Chrome and clicking the link will work as expected.

**Smartphone (please complete the following information):**
 - Device: Galaxy S10
 - OS: Android 11
 - App Version - v4.2.2 (834)

**Comment by bangtoven** [comment]
hi @jamiely thanks for reaching out.
yes, we are aware of the issue of returning deep links.
https://docs.cloud.coinbase.com/wallet-sdk/docs/deep-link-into-dapp-browser
you can set a deep link scheme to be allowed by providing `cb_callback` parameter on android starting next release.

**Comment by bangtoven** [comment]
> On Android, you may pass the optional parameter cb_callback into the universal link to open a custom scheme for callback: https://go.cb-w.com/dapp?cb_url=[YOUR_URL]&cb_callback=[YOUR_CALLBACK_SCHEME]

**Comment by jamiely** [comment]
@bangtoven awesome, thank you very much! Any approximate idea when the next release will be?

**Comment by bangtoven** [comment]
hey @jamiely 
well, it seems it will start rolling out early april.

**Comment by jamiely** [comment]
@bangtoven I just tried this on version 26.7.427. Should it work? I wasn't able to get it to work. If it should work, can you give me an example of a callback scheme that should work?

For example I think I should be able to open a URL like `vnd.youtube://youtu.be/OgO1gpXSUzU` on a webpage by passing cb_callback=vnd.youtube. Clicking a link with URL like the one above in Chrome would open the Youtube app..

**Comment by bangtoven** [comment]
hey @jamiely 
the change will be on 26.8.x release, which we paused rollout due to some bugs. 
26.8.431 will be out soon.
thank you.

**Comment by QuintonC** [comment]
@bangtoven Hey there 👋 

I'm on the same team as Jamie and we're experiencing this issue again in the most recent version of Coinbase. Is this something that is being monitored by chance?

Thanks!

**Comment by bangtoven** [comment]
hey @QuintonC 
thanks for flagging this and i am sorry that this issue came back.
we realized that there was a regression on this part of the app and our team is working on a fix right now. 
will let you know once we have updates.
thanks!

**Comment by QuintonC** [comment]
> hey @QuintonC thanks for flagging this and i am sorry that this issue came back. we realized that there was a regression on this part of the app and our team is working on a fix right now. will let you know once we have updates. thanks!

Thanks @bangtoven!

If it helps here is some of the behavior that I noticed through debugging our app today:
- Deep links no longer work on iOS. Universal links kind of work.
- We can no longer programmatically call `window.location.assign(url)` to automatically redirect our users back into our app.
- Universal links work on iOS
- Android doesn't seem to work for either deep links or universal links

Also, out of curiosity, I was wondering if you had a contact which I could speak with about some other debugging assistance for our team.

Thanks again!

**Comment by taycaldwell** [comment]
@QuintonC I reached out via Twitter DM with contact details for debug assistance.

**Comment by bangtoven** [comment]
hi @QuintonC thanks for your patience.
can you try the new 28.4.6 please? also, we made some updates so that you don't need to pass the cb_callback param anymore. let us know how it works.

**Comment by QuintonC** [comment]
> hi @QuintonC thanks for your patience. can you try the new 28.4.6 please? also, we made some updates so that you don't need to pass the cb_callback param anymore. let us know how it works.

Hey, sorry for the delay @bangtoven

This seems to be working as expected now. The one interesting thing though is that we were unable to get our callbacks to initiate automatically on iOS if we were using universal links. With deep links it appears to be working though.
