### ISSUE TITLE
[spam]

### ISSUE THREAD

**Issue by Suriyakaenjanya** [coinbase/coinbase-wallet-sdk#438]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Suriyakaenjanya** [comment]
kaenjanya.in.th@gmail.com

**Comment by DanielaDudyova** [comment]
Heloo
