### ISSUE TITLE
[UX] Don't force user to leave Dapp on tx

### ISSUE THREAD

**Issue by pi0neerpat** [coinbase/coinbase-wallet-sdk#44]
### Current behavior

When I submit a transaction, I am forced to leave the dapp browser. Likely this is leftover from early dapp days, when most dapps did not track transaction progress.  

### Expected behavior

Make the default behavior to stay on the dapp browser page. Many dapps track tx progress now, and its very bad experience to "rip" them away.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. 
i suppose this issue had been addressed already.
please open a new one if needed. thanks.
