### ISSUE TITLE
Wrong signature when signing message?

### ISSUE THREAD

**Issue by bonustrack** [coinbase/coinbase-wallet-sdk#45]
I'm using Walletlink in https://demo.snapshot.page to sign message but for some reason the signature created by is diffent than Metamask, i canot validate the signed message if it come from Walletlink. Any idea whats wrong? Do you have existing app using signing message ability?

**Comment by jurosh** [comment]
Same issue here... signature seems to be incorrect for some reason. Using `Walletlink` with `ethers.js` web3 provider...

I see that in repo are already more opened issues without any answer.. is Walletlink not maintained anymore ?

**Comment by tsudmi** [comment]
Would it be possible to switch to a standard signatures format?

**Comment by redben** [comment]
> Same issue here... signature seems to be incorrect for some reason. Using `Walletlink` with `ethers.js` web3 provider...
> 
> I see that in repo are already more opened issues without any answer.. is Walletlink not maintained anymore ?

Setting provider.isMetaMask to true should fix it. Also redefine the property as it is not writable:
 Object.defineProperties(walletconnectProvider, { isMetaMask: { value: true} })

**Comment by germanllop** [comment]
> > Same issue here... signature seems to be incorrect for some reason. Using `Walletlink` with `ethers.js` web3 provider...
> > I see that in repo are already more opened issues without any answer.. is Walletlink not maintained anymore ?
> 
> Setting provider.isMetaMask to true should fix it. Also redefine the property as it is not writable:
> Object.defineProperties(walletconnectProvider, { isMetaMask: { value: true} })

This worked like a charm, can you explain what wrong with the other way please?

**Comment by redben** [comment]
I don't remember exactly but i:t has to do with this
 https://github.com/ethers-io/ethers.js/blob/d3b7130ed6ec50b192eb7f33905eaa327d65eee2/packages/providers/src.ts/web3-provider.ts#L35

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please open a new one if needed. thanks.
