### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Newman1515** [coinbase/coinbase-wallet-sdk#460]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kyokosdream** [comment]
Completely useless Github issue opened by @Newman1515 . It is literally a complete copy and paste of the Bug Report template with ZERO information. Please close this issue so this repo can actually be maintained and serviced by people not just trying to troll.

**Comment by ljharb** [comment]
Please fill out the issue template.
