### ISSUE TITLE
Please explain what tracking your app does

### ISSUE THREAD

**Issue by bnolan** [coinbase/coinbase-wallet-sdk#462]
When sharing a URL in the iOS app the shared url goes to a link tracking service. Can you confirm what other URLs you are tracking in the app?

https://twitter.com/bnolan/status/1513282054967812102

**Comment by bnolan** [comment]
I would also ask to let me log in using safari on iOS instead of forcing your app that tracks me.

**Comment by brianchitester** [comment]
Hi @bnolan, thank you for your question, we take our customer's privacy very seriously at Coinbase.  

You can read more about our app's privacy practices directly in the app store, or refer to our [privacy policy](https://wallet.coinbase.com/privacy-policy). I've included a screenshot below with a brief summary of our App Privacy statement from the App store.

![Image from iOS (6)](https://user-images.githubusercontent.com/311848/174138791-bbc6b880-a82e-491e-b072-573d893972d9.png)
