### ISSUE TITLE
Add Ubiq Mainnet

### ISSUE THREAD

**Issue by iquidus** [coinbase/coinbase-wallet-sdk#467]
Ubiq is an EVM compatible chain launched in 2017. Dapps on the network have recently begun integrating coinbase wallet support (with users adding Ubiq as a custom network).

What is required to add Ubiq to the list of whitelisted networks/default mainnets?

name: Ubiq
chainId: 8
public rpc endpoint: https://rpc.octano.dev
symbol: UBQ
explorer: https://ubiqscan.io

Saw this comment https://github.com/coinbase/coinbase-wallet-sdk/blob/master/src/EthereumChain.ts#L1 so figured we should discuss before submitting a PR.

Thanks

**Comment by bangtoven** [comment]
hi. sorry for the belated response. 
this sdk is responsible mostly for a transport layer, and managing networks/chains happens on the cbwallet app. cbwallet supports adding custom chains.
please try our latest version 3.6.0. feel free to open a new issue if needed. thanks.
