### ISSUE TITLE
unsupported methods fails violently

### ISSUE THREAD

**Issue by Amxx** [coinbase/coinbase-wallet-sdk#47]
I noticed that some methods are not available. In particular:
- eth_chainId
- personal_sign
- eth_signTypedData_v3

While I understand that not all methods are implemented (chainId is a shame, as it shouldn't be that hard to implement) ... my biggest issue is that this fails violently. I'm can't even manage to catch it! Is that a known issue?

**Comment by zakpie** [comment]
Check our wrapper here incase it solves the issues: 
https://github.com/LibertyPie/Wallet-Provider

**Comment by petejkim** [comment]
Hmm... not entirely sure what you mean by failing violently, but personal_sign and eth_signTypedData_v3 should work. We will add eth_chainId, but in the mean time you should be able to use net_version (which isn't exactly the same thing, but close enough)

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please open a new one if needed. thanks.
