### ISSUE TITLE
web3provider has no `.on()` endpoint

### ISSUE THREAD

**Issue by Amxx** [coinbase/coinbase-wallet-sdk#48]
web3.on is commonly used by frontend to adapt to wallet events.

It not being avaialble on walletlink breaks a lot of assumption dapps usually have about providers.

**Comment by ScorpionKing** [comment]
How do I get event about change chain or disconnect wallet?

**Comment by zakpie** [comment]
Hello  we had the same issue, we have created a wrapper to interact with Wallet Link including multiple wallets, check it here: https://github.com/LibertyPie/Wallet-Provider
W have provided a little work around for .on() events

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please open a new one if needed. thanks.
