### ISSUE TITLE
[Android SDK] Provide SDK for Android client

### ISSUE THREAD

**Issue by amilcar-andrade** [coinbase/coinbase-wallet-sdk#482]
### Describe the solution you'd like

The following SDK (https://github.com/coinbase/coinbase-wallet-sdk) was providing some of this functionality. We are wondering what is the recommended approach now and if there is a test android app that we can use as a starting point.

### Describe alternatives you've considered

Using wallet connect API

**Comment by bangtoven** [comment]
Hi. 
Our Mobile Wallet Protocol supports this: https://coinbase.github.io/wallet-mobile-sdk/docs/client-sdk/rn-install
