### ISSUE TITLE
Bug: Transactions stuck "Pending" despite success

### ISSUE THREAD

**Issue by kyokosdream** [coinbase/coinbase-wallet-sdk#485]
### Describe the bug

Transactions in my Coinbase Wallet Chrome extension are stuck in "Pending" state even with 80+ block confirmations.

### Steps

1. Deploy a transaction 
2. Observe transaction in Chrome extension 
3. Click on "View on Tx Explorer" to view the transaction on a block explorer 
4. Observe that the transaction has been processed successfully with many block confirmations 
5. Observe that Coinbase Wallet still shows the transaction in "Pending" state. 

### Expected behavior

The transaction state in the extension should be marked as Completed immediately upon transaction success or after a small number of block confirmations. 

### Version

3.0.8

### Additional info

Incongruency is leading to a lack of trust between our users and dapp and we are considering dropping support for Coinbase Wallet until the issue is resolved.

### Desktop

OS: Ubuntu 20.04 Focal Fossa 
Browser: Chrome

**Comment by kyokosdream** [comment]
Also, for a company valued at nearly $100 billion, can you guys do a better job policing these Github issues. Issues left unanswered for months and some useless issues need to be deleted.

**Comment by kyokosdream** [comment]
I would like to add that this issue persists across multiple chains and never resolves itself. After 5 hours and 2700+ block confirmations I am still seeing the issue.

**Comment by L03TJ3** [comment]
I would like to add, which I believe to be aligned with this issue.
While using block-native onboard to connect to coinbase wallet, and being connected to a custom network
logs show a PollingBlockTrackerError where it cannot update to the latest block (undefined).

Where the dapp itself IS able to fetch the latest block data.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
