### ISSUE TITLE
Bug: missing svgs

### ISSUE THREAD

**Issue by sgehrman** [coinbase/coinbase-wallet-sdk#497]
### Describe the bug

I see a png, but no svg

### Steps

If you focused more time on the contents of this repo and less time on silly questionaries, I wouldn't have to report this.

coinbase_wallet_logo.png?  Where's the svg version? 

### Expected behavior

coinbase_wallet_logo.png?  Where's the svg version? 

### Version

2

### Additional info

coinbase_wallet_logo.png?  Where's the svg version? 

### Desktop

coinbase_wallet_logo.png?  Where's the svg version? 

### Smartphone

coinbase_wallet_logo.png?  Where's the svg version?

**Comment by jeongmincho** [comment]
Please see: https://github.com/coinbase/coinbase-wallet-sdk/raw/master/assets/coinbase_wallet_logo_kit.zip
