### ISSUE TITLE
Bug: TypeError: util.inherits is not a function

### ISSUE THREAD

**Issue by samuveth** [coinbase/coinbase-wallet-sdk#498]
### Describe the bug

I see the following error in the console when I click on the coinbase connector

### Steps

<img width="508" alt="image" src="https://user-images.githubusercontent.com/51686767/166184612-670c1707-2c39-42e8-9881-ed441a6f725c.png">

### Expected behavior

The coinbase wallet connector modal should open where I can scan the QR code to login.

### Version

v3.0.11

### Additional info

Vite, Vue 3, typescript

**Comment by ljharb** [comment]
It’ll work fine in any working node module bundler.
