### ISSUE TITLE
Bug: Unable to use signTypedData_v4 in snapshot.org

### ISSUE THREAD

**Issue by midgerate** [coinbase/coinbase-wallet-sdk#508]
### Describe the bug

In the compiled version of snapshot, I see an error but it works fine when running locally in dev

### Steps

FYI - This might be snapshot.org specific problem, however it affects a large number of users of snapshot.org

1. Go to this URL https://snapshot-ztk9cr4q9-snapshot.vercel.app/#/pistachiodao.eth/proposal/0x08c3bd2960700525770a1d634f8599ba967e55fcc05b6c1649d984d88253769d
2. Connect with Coinbase wallet and try to vote
3. You will see an error in console

![image](https://user-images.githubusercontent.com/91108642/167283541-54bbc361-7b66-47d7-990a-ed2818bc75d4.png)

This only happens on build version and does not happen on development mode. 

Here's how we create the provider (its inside @snapshot-labs/lock package)
![image](https://user-images.githubusercontent.com/91108642/167283585-e426364d-a225-4a8d-8394-bbb197c65b2f.png)

Here's how we get the signer (its inside @snapshot-labs/snapshot.js package)
![image](https://user-images.githubusercontent.com/91108642/167283567-66321455-c3ce-48f8-8f00-3fdef591c900.png)

### Expected behavior

It should open the confirmation in the mobile phone app. 

### Version

3.0.11

### Additional info

FYI - I haven't tested this with the coinbase wallet chrome extension. 

### Desktop

- Browser - Chrome

### Smartphone

- OS Android

**Comment by macky22am** [comment]
Is this about me?

**Comment by macky22am** [comment]
Bug

**Comment by samuveth** [comment]
Any update on this?

**Comment by bonustrack** [comment]
You can reproduce the issue on this proposal https://snapshot-ztk9cr4q9-snapshot.vercel.app/#/pistachiodao.eth/proposal/0x08c3bd2960700525770a1d634f8599ba967e55fcc05b6c1649d984d88253769d just connect wallet select a choice and try to vote and you should see the error in the console

**Comment by taycaldwell** [comment]
Coinbase Wallet supports both **eth_signTypedData_v3** and **eth_signTypedData_v4**.

Can you please clarify -
1. Are you testing using the Coinbase Wallet mobile app, or the browser extension?
2. What version(s) are you using for testing?

**Comment by samuveth** [comment]
@taycaldwell The issue occurs when you connect with the mobile app to a desktop running snapshot in chrome via QR code scan.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. 
please try the latest CBWallet mobile app with version 28.23. 
feel free to open a new one if needed. thanks.
