### ISSUE TITLE
WalletLink insert HTML outside of body

### ISSUE THREAD

**Issue by jurosh** [coinbase/coinbase-wallet-sdk#51]
By using walletlink like this (on demand)
```
const WalletLink = (await import('walletlink')).default;
const walletLink = new WalletLink({ appName: '...', appLogoUrl: '...' });
```
It seems to insert it's `style` and `html` outside of body, which breaks stuff as it's not valid HTML.

![image](https://user-images.githubusercontent.com/1630137/95212173-b4639200-07ed-11eb-9c21-928d6f1d2110.png)

Using latest `walletlink@2.0.2`

Walletlink have to insert it's HTML & STYLE only inside of BODY. Otherwise it will produce incorrect HTML which might not work.

**Comment by petejkim** [comment]
This was to prevent web frameworks that try to re-render the entire content of the body from removing walletlink's html, most browsers are forgiving and this shouldn't result in issues though. Are you running into any issues?

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
