### ISSUE TITLE
Bug: Library does not work under strict Content-Security-Policy

### ISSUE THREAD

**Issue by joestakey** [coinbase/coinbase-wallet-sdk#520]
### Describe the bug

Library does not work under strict Content-Security-Policy

### Steps

Because of the dependency to `js-sha256`, the package does not work when the Content-Security-Policy does not include `unsafe-eval`. (see [this issue](https://github.com/emn178/js-sha256/issues/26) in js-sha256)

### Expected behavior

@coinbase/wallet-sdk should be able to work under CSP, remove packages that use `eval()`

### Version

3.1.0

**Comment by macky22am** [comment]
Bug

**Comment by Kosratali10** [comment]
Sir please please help me how i can get came back my money

**Comment by brianchitester** [comment]
Fixed with #577 released in v3.4.0

**Comment by Kosratali10** [comment]
What do you mean now please i need help you
