### ISSUE TITLE
connector modal not opening on my setup. works on codesandbox

### ISSUE THREAD

**Issue by sriksm19** [coinbase/coinbase-wallet-sdk#53]
walletlink connector modal doesnt open up on my local project, but works with the same version here: https://codesandbox.io/s/github/NoahZinsmeister/web3-react/tree/v6/example

after digging deep, i found out that the module (`url`) within the file `dist/relay/WalletLinkRelay.js`, thats getting resolved here doesnt have the `.default` field, and hence it gracefully throws an error at that point. once i remove the default n then start up my app, the modal works fine. 
![image](https://user-images.githubusercontent.com/1223117/97322485-dc4a9080-1895-11eb-9d60-04fa96c5dbc3.png)

apparently all other dependency packages work fine, except for this.

i use typescript (tried with 3 and 4) and the project is based out of preact-cli. also tried with the same tsconfig that's found in this project, still the same. any clue?

**Comment by petejkim** [comment]
`allowSyntheticDefaultImports` in tsconfig may fix your issue

**Comment by petejkim** [comment]
I believe this is because walletlink expects node polyfills to be available. Related: #56.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
