### ISSUE TITLE
Make possibility to use own custom QR code modal window

### ISSUE THREAD

**Issue by alsakhaev** [coinbase/coinbase-wallet-sdk#55]
### Problem
We develop a browser extension. Usually, they consist of several parts: background, inpage script, popup etc (see the picture below).
![image](https://user-images.githubusercontent.com/15713727/100442426-0a033f00-30b9-11eb-881c-eda196391f48.png)
We'd like to create an instance of WalletLink inside the background, but during paring there is no posibillity to show QR code to an user, because the background doesn't have a representation layer despite the fact that it has own DOM. 

### Possible Solution
Possibly to make a some hook, which fires in the moment of pairing.
It might look like this:

```javascript
// Initialize WalletLink
const walletLink = new WalletLink({
  appName: APP_NAME,
  appLogoUrl: APP_LOGO_URL,
  darkMode: false,
  qrcode: false // disables injecting of the modal window into the DOM
})

// Subscribe to QR code displaying event
walletLink.on("display_qrcode", (url) => {
  // e.g. url = "https://www.walletlink.org/#/link?id=0000&secret=0000&server=https%3A%2F%2Fwww.walletlink.org&v=1"
  showCustomQR(url);
});
```
But your WallletLink instance doesn't have any subscription methods like 'on()', and it looks like such a solution doesn't fit into your architecture.
It would be great to discuss where and how is better to make such feature within your application architecture. 
I could help to implement this and make a PR.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
