### ISSUE TITLE
Remove the need for Node.js polyfills

### ISSUE THREAD

**Issue by bpierre** [coinbase/coinbase-wallet-sdk#56]
WalletLink relies on native Node modules, which means that bundlers are responsible to provide polyfills for these modules. This can be problematic for several reasons:

- Some bundlers don’t provide polyfills by default (e.g. Webpack 5, Snowpack).
- These polyfills can be huge (e.g. with [crypto-browserify](https://bundlephobia.com/result?p=crypto-browserify@3.12.0)), and are often not using the native browser APIs like `window.crypto`.
- These polyfills can be implemented in various ways, which impacts WalletLink robustness, stability and security for end users.

If the intent is to maintain a compatibility between Node and browsers, I would suggest to add another entry point for it (e.g. `src/index-browser.ts` => `dist/index-browser.js`). It would make it possible to provide different implementations between Node and the browser when needed.

Here is a list of native Node modules used by WalletLink, and suggestions on what could be done to support browser environments.

@petejkim let me know what you think! :slightly_smiling_face: 

## url

The `url` module is only used once [to parse a URL](https://github.com/walletlink/walletlink/blob/ffc86286a1692334523783257d1da68f11a0043b/js/src/relay/WalletLinkRelay.ts#L90). This one is easy, as both Node and browser environments provide a globa `URL` object that can do the same thing without having to import any module:

```tsx
const url = new URL(this.walletLinkUrl)
this.walletLinkOrigin = `${url.protocol}//${url.host}`
```

### crypto.randomBytes()

This is used in a few places:

https://github.com/walletlink/walletlink/blob/ffc86286a1692334523783257d1da68f11a0043b/js/src/relay/WalletLinkRelay.ts#L303

https://github.com/walletlink/walletlink/blob/ffc86286a1692334523783257d1da68f11a0043b/js/src/relay/Session.ts#L28-L29

https://github.com/walletlink/walletlink/blob/ffc86286a1692334523783257d1da68f11a0043b/js/src/relay/aes256gcm.ts#L8

As an example, here is a Node-only function that could be used in these cases:

```ts
const crypto = require('crypto')

function randomBytesHex(length) {
  return crypto.randomBytes(length).toString("hex")
}
```

And here is how we could implement a browser equivalent:

```js
function randomBytesHex(length) {
  return uint8ArrayToHex(crypto.getRandomValues(new Uint8Array(length)))
}

// This function is needed because browser’s crypto.getRandomValues()
// return a Uint8Array while Node’s crypto.randomBytes() returns a Stream.
function uint8ArrayToHex(value) {
  return [...value].map(b => b.toString(16).padStart(2, '0')).join('')
}
```

Another solution could be to use the [uuid module](https://github.com/uuidjs/uuid). It works in Node and browser environments, and the version 4 (random) UUID would help in cases where a unique ID of any size is needed.

### crypto.createCipheriv()

This is used in the `aes256gcm.ts` module, to encrypt and decrypt:

https://github.com/walletlink/walletlink/blob/ffc86286a1692334523783257d1da68f11a0043b/js/src/relay/aes256gcm.ts#L9-L13

Browsers provide the [`window.crypto.subtle.encrypt()`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt) and [`window.crypto.subtle.decrypt()`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/decrypt) methods.

The AES-GCM algorithm is supported: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt#AES-GCM

And here is an example on how to use it: https://github.com/mdn/dom-examples/blob/a7e751ff4b82cc19bd3b7451897c254ebe78ebd5/web-crypto/encrypt-decrypt/aes-gcm.js

The two APIs are quite different here, so I think it could be a good idea to provide a browser-only version of `aes256gcm.ts`, that would be injected from the entry point.

Another solution could be to use a module like [`@peculiar/webcrypto`](https://github.com/PeculiarVentures/webcrypto), which provides a Node polyfill for the WebCrypto API. It has a cost in terms of performances and [bundle size](https://bundlephobia.com/result?p=@peculiar/webcrypto@1.1.4), but it would allow to use the same API for both Node and the browser.

## keccak

The keccak module already provides a version for browsers:

https://github.com/cryptocoinjs/keccak/blob/e77962484b20fe3c1ca3ddd7e3f455bb118cc545/package.json#L22-L25

The issue is that only the Node version is being used by WalletLink:

https://github.com/walletlink/walletlink/blob/ffc86286a1692334523783257d1da68f11a0043b/js/src/vendor-js/keccak/index.js

I would recommend to either move it as an external dependency (to preserve the package.json fields), or to reproduce this internally by having the browser version in `src/vendor-js/keccak` and import it from the WalletLink browser entry point.

**Comment by aksdevac** [comment]
This is also needed for official angular support with current Angular CLI, node specific dependency are not included /supported for browser, also commonjs modules are also not recommended by Angular.

**Comment by petejkim** [comment]
Thanks for the suggestion, we will look into this

**Comment by REPTILEHAUS** [comment]
+1 for this also for Angular CLI project

**Comment by fubhy** [comment]
We are also running into this issue.

In addition to the obvious problem with the Node dependencies that make this package unusable e.g. with Snowpack, I'd also love to see a bit of a leaner package overall. Right now the dependency chain that comes with this package is quite huge and accumulates to a whopping ~500kb of extra dependencies after bundling.

I'd suggest to also consider dropping some of those and then exporting an ESM entrypoint.

Furthermore it would be nice for the package to not pollute the global namespace with type declarations (https://github.com/walletlink/walletlink/blob/master/js/src/index.ts#L12-L18). Those should be an internal implementation detail and not included in the published types.

**Comment by TimDaub** [comment]
> It would be nice to not have a hard dependency on RxJs and Preact.

I came here because [walletlink's bundle size](https://bundlephobia.com/result?p=walletlink@2.1.0) scares me away from using it.

**Comment by fubhy** [comment]
Ping @hieronymus777 - Any plans on fixing these problems? Our token has recently been listed on Coinbase Pro and we'd love to also enable Coinbase Wallet support via WalletLink on our app but this issue is preventing us from doing so. (see https://github.com/walletlink/walletlink/issues/56#issuecomment-801240970).

We'd need to

a) Get rid of the node dependencies (this is meant to be used in the browser after all)
b) Drastically reduce the bundle size (remove unnecessary bloat)

Not doing these cleanups prevents most of / all of the modern tools out there to work with this including Snowpack, Vite, Esbuild, Swc, etc.

As more and more apps are migrating to those for obvious reasons fixing your dependency tree should be a high priority imho.

**Comment by TimDaub** [comment]
FYI, I believe that this wallet provider code has taken a wrong turn somewhere. How can it be that dependency trees for anything Ethereum related are huge when infact they wouldn't have to be. I've built a focused component for Metamask that is just a few bytes - no ethersjs, web3 or any of that jazz...

https://github.com/rugpullindex/web3-sign-msg

I think we should really try to subtract instead of add.

**Comment by fubhy** [comment]
> FYI, I believe that this wallet provider in web3 code has generally taken a wrong turn somewhere. How can it be that dependency trees for anything Ethereum related are huge when in fact they don't have to be? I've built a focused component for Metamask that is just a few bytes - no ethersjs, web3 or any of that jazz...
> 
> * https://github.com/rugpullindex/web3-sign-msg
> * https://rugpullindex.github.io/web3-sign-msg/
> 
> I think we should really try to subtract instead of add.

Absolutely. There's EIP1193 for a reason.

**Comment by fubhy** [comment]
Hi @brendanww. That's a good first step, thanks for working on this! Is my interpretation of your comment correct that you're still planning to also remove the other node dependencies?  Webpack is not really an option for us as well as any application that's built around more modern tools like esbuild, swc, vite, snowpack, etc.

**Comment by brendanww** [comment]
@fubhy that's correct. which build tool are you using?

**Comment by fubhy** [comment]
> @fubhy that's correct. which build tool are you using?

Awesome. That's great to hear! We are using Vite (with React).

**Comment by CRodrigo210** [comment]
#54

**Comment by talentlessguy** [comment]
Is it possible to replace `keccak` with [node-sha3](https://github.com/phusion/node-sha3)

Currently wallet sdk breaks on `pnpm` installations because of the keccak module.
