### ISSUE TITLE
Bug: eth_requestAccounts not involve coinbase extension modal in iframe

### ISSUE THREAD

**Issue by ArtemFokin** [coinbase/coinbase-wallet-sdk#578]
### Describe the bug

I use web3-react v6 and walletlink connector and our app running in iframe(shopify admin panel). Nothing happend after i clicked on coinbase button. I also try to trigger eth_requestAccounts dirictly with same result. When i open page without iframe -  coinbase extensions works well.

### Steps

Open some dapp in iframe and click on connect Coinbase Wallet

### Expected behavior

i expect that it's would connect with extension as good as on pages without iframe.

Or 

Add a flag to disable extension check and just open qr-modal. i'm tryed to remove window.ethereum, but it didn't help.

We would like to add coinbase wallet for our customers, hope this get fixed.

**Comment by lfsalazarcruz** [comment]
I'm having the exact same issue. Trying to open coinbase wallet extension from an <iframe/> and nothing happens. Getting ERR_BLOCKED_BY_CLIENT when clicking coinbase login button and it's not activating the wallet. Works well outside of iframe. MetaMask works well running in and out of iframe.

**Comment by JacobMuchow** [comment]
This would be really helpful. We are building a product that can be embedded into any website. We can't do 1st party support for Coinbase Wallet for the time being.

**Comment by taycaldwell** [comment]
Closing as duplicate. This issue is now being tracked here: https://github.com/coinbase/coinbase-wallet-sdk/issues/588
