### ISSUE TITLE
Feature Request: Allow provider to be used for unknown addresses

### ISSUE THREAD

**Issue by mds1** [coinbase/coinbase-wallet-sdk#580]
### Describe the solution you'd like

I'm one of the developers of [Umbra](https://app.umbra.cash/), a stealth payments protocol. Stealth payments require access to private keys, so we ask the user to sign a message then generate an app-specific private key from that signature, and the corresponding app-specific public key is published on-chain in a registry. (More info can be found in the [FAQ](https://app.umbra.cash/faq)).

When someone sends you funds, a new, one-time use stealth address is computed by the sender using that public key, and your app-specific private key is used to compute the private key to that stealth address. To withdraw those funds from the stealth address to some other address, the Umbra app computes that private key, signs the transaction, and submits it.

We submit the transaction to the provider obtained when the user connected their wallet. Recently, we've received reports of Coinbase wallet users (using the browser extension) who are unable to withdraw funds. They see an error message of "User rejected request", which doesn't make sense given that the app-specific private key is in memory so the user never had to approve/reject a transaction request.

From digging around in this codebase, I think what is happening is the following:
- The Umbra app sends the transaction via ethers with `eth_sendTransaction` which is handled by coinbase [here](https://github.com/coinbase/coinbase-wallet-sdk/blob/d3d414e246e9fff2b94d825d30c5f773cf529ed3/src/provider/CoinbaseWalletProvider.ts#L1041).
- The second line of that method calls `_prepareTransactionParams`.
- `_prepareTransactionParams` calls `_ensureKnownAddress`, and obviously this address is not known to the wallet because it's a stealth address, so it throws an error and rejects the transaction.
- I'm not certain how that CoinbaseWalletProvider bubbles that error into WalletSDKRelay, but it seems that in WalletSDKRelay the `UserRejectedRequest` error is the [fallback](https://github.com/coinbase/coinbase-wallet-sdk/blob/d3d414e246e9fff2b94d825d30c5f773cf529ed3/src/relay/WalletSDKRelay.ts#L797). So my current best guess is the error is the `ensureKnownAddress` error isn't being bubbled up properly and the user sees "User rejected request".

So this "feature request" is really two questions:
1. Is my assessment of this bug correct, or is there some other reason the user is seeing this error?
2. If correct, is there a way we can support this? Of course, we can fallback to our own provider if the user's wallet's provider rejects the transaction, but ideally we wouldn't have to do that.

An image of the user's console is below.

![image](https://user-images.githubusercontent.com/17163988/174888036-88c9622a-989a-4c96-b917-b17ad59549d6.png)

Thanks!

**Comment by Brentus1** [comment]
https://github.com/coinbase/coinbase-wallet-sdk/labels/type%3A%20enhancement

**Comment by bangtoven** [comment]
hi @mds1 , sorry for the long overdue response. 
i think your assessment is correct, and the SDK is not surfacing internal errors properly.
we will get this addressed in next releases.
thank you for reporting this.
