### ISSUE TITLE
Bug: Coinbase wallet extension not activating in iframe. MetaMask activates 

### ISSUE THREAD

**Issue by lfsalazarcruz** [coinbase/coinbase-wallet-sdk#588]
### Describe the bug

Our app is running inside an iframe. Nothing happens after i click Coinbase login button. When i open the main app without an iframe - Coinbase extensions works well.

### Steps

Open an app inside an <iframe/> and try to activate/connect to coinbase wallet extension.

### Expected behavior

Coinbase wallet extension should popup and allow me to connect to my app.

### Version

Coinbase wallet extension 2.21.1

### Additional info

Sometimes I get ERR_BLOCKED_BY_CLIENT when trying to connect 

### Desktop

chrome Version 103.0.5060.53 (Official Build) (x86_64)
macos monterrey 12.3.1

**Comment by JacobMuchow** [comment]
This would be really helpful. We are building a product that can be embedded into any website. We can't do 1st party support for Coinbase Wallet for the time being.

**Comment by iandjx** [comment]
Would at least like to know if this issue will be fixed or not. Thanks.

**Comment by taycaldwell** [comment]
Hello, I can confirm we are tracking this and actively looking into a fix for addressing this issue.

**Comment by taycaldwell** [comment]
This issue has been addressed in the latest version of the Coinbase Wallet browser extension.
