### ISSUE TITLE
Don't redirect the user to download wallet if they are in a CipherWebView (CB Wallet Mobile)

### ISSUE THREAD

**Issue by gareys-cb** [coinbase/coinbase-wallet-sdk#593]
Today, if the user is in the Coinbase Wallet App, there is a chance that the dapp will attempt to requestEthereumAccounts before the web view provider has initialized. In this case, the CB Wallet SDK redirects the user to download the app (see referenced line). We don't want to do that since the user already has the app. I'm not sure how we will differentiate between CB Wallet's mobile WebView and other user-agents. Perhaps we can pass a configuration variable to the Wallet SDK Provider that we inject into the web view. @jeongmincho @bangtoven

https://github.com/coinbase/coinbase-wallet-sdk/blob/84ddf4a910d820319a255a75f34d11fdfddffe3c/packages/wallet-sdk/src/relay/WalletSDKRelay.ts#L847-L857

**Comment by cb-jake** [comment]
We have an `isCoinbaseBrowser` flag that is defaulted to `true` inside of the web views provider.
