### ISSUE TITLE
Android: Deeplinking to CBW doesn't redirect after signing the message

### ISSUE THREAD

**Issue by lub0s** [coinbase/coinbase-wallet-sdk#597]
### Describe the bug

The WebView used in the Android CWB doesn't redirect into calling app

### Steps

1. Start Intent using `https://go.cb-w.com/dapp?cb_url=$url&cb_callback=$callback` as Uri
2. Sign message 
3. The app doesn't redirect to the calling app
4. The CWB redirect ignores cb_callback 

### Expected behavior

The Android CWB should redirect user to the calling app 
the 

### Additional info

Sample:
```
val url = Uri.encode("https://c.e.x/wallet?message=aaaaaaaa")
val callback = Uri.encode("c://dapp")
val uri = Uri.parse("https://go.cb-w.com/dapp?cb_url=$url&cb_callback=$callback")
val intent = Intent(Intent.ACTION_VIEW, uri)
localContext.startActivity(intent)
```
The URL in the app's browser doesn't start with custom scheme after signing the message 

### Smartphone

- Samsung S20

**Comment by vishnumad** [comment]
@lub0s could you let me know which version of the Coinbase Wallet app you're using? You can find this in the "Settings" tab near the bottom.

**Comment by lub0s** [comment]
@vishnumad the version is 28.2.7

**Comment by QuintonC** [comment]
Also experiencing this on Android.

Callback URLs are formatted as: `appBundle://path/paramsHere`, but we receive the following (image attached)

![Screenshot_20220810-012715_Wallet](https://user-images.githubusercontent.com/4250423/183734158-1564e049-ed50-4397-aa94-30e8f6ed13cd.jpg)

**Comment by bangtoven** [comment]
hi. sorry for the belated response. i believe this deeplinking callback with custom scheme issue had been addressed in previous releases. please try our latest version 28.22.0. feel free to open a new one if needed. thanks.
