### ISSUE TITLE
Bug: Can't figure out my balance on dapp after connect coinbase wallet.

### ISSUE THREAD

**Issue by CutupAngel** [coinbase/coinbase-wallet-sdk#599]
### Describe the bug

Can't figure out the balance after connect wallet and dapp.

### Steps

1. Go to app.arc.market on mobile.
2. Connect wallet and dapp.
3. Can't figure out balance after that.  With the other wallet works fine.

Looking forward to hearing good answers!!!

### Expected behavior

Can't figure out the balance.

**Comment by taycaldwell** [comment]
Unable to reproduce. Please provide more details.

<img width="1790" alt="Screen Shot 2022-07-20 at 10 34 34 AM" src="https://user-images.githubusercontent.com/3264051/180046353-aa0b613f-601b-4c4a-95f8-a8839f3b16b9.png">

1. What version of the Coinbase Wallet browser extension are you using?
2. What assets are you checking the balance of?
3. What chain are you connecting to?

**Comment by CutupAngel** [comment]
Thanks for your kindness.

1. I used android mobile application to connect dapp.
2. I can't figure out any balance.
3. First of all, I tried to use Ethereum.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
