### ISSUE TITLE
Bug: android native sample seems not work

### ISSUE THREAD

**Issue by anonymouslystudio** [coinbase/coinbase-wallet-sdk#604]
### Describe the bug

android native sample won't connect the wallet

### Steps

run android native sample
click connect button
coinbase wallet was pulled up and nothing goes on, no connection dialogs and no errors

### Expected behavior

pull up coinbase. wallet and connect dialog display
then when choose connect , response back

**Comment by mzmti** [comment]
I'm facing the same issue. Testing using the latest android build of coinbase wallet 26.12.440.

**Comment by vishnumad** [comment]
Hey all, thanks for your interest in the native SDK. We're still in the process of adding support for it in the CB Wallet mobile apps. We're targeting August for the update. I can post an update in this issue once it's ready.

**Comment by vishnumad** [comment]
Version 28.4.4 of the Coinbase Wallet app adds support for the native sdk
