### ISSUE TITLE
Bug: unable to fetch balance

### ISSUE THREAD

**Issue by amrap030** [coinbase/coinbase-wallet-sdk#605]
### Describe the bug

In my application, after connecting to the wallet, I am fetching the user's balance. However, this request fails because of the following error (see Additional Info). I am using the default RPC URL for Polygon Mumbai Testnet, that is provided with the coinbase wallet chrome extension. I also tried different RPC Url's with no luck. My coinbase wallet version is 2.23.2.

### Steps

1. Connect to wallet
2. Immediately fetch balance of user via `getBalance()` function

### Expected behavior

The expected behavior would be to fetch the balance with no errors.

### Version

3.2.0

### Additional info

Error:

<img width="863" alt="Bildschirmfoto 2022-07-27 um 00 11 52" src="https://user-images.githubusercontent.com/35061229/181121323-bae393c3-7e57-49ed-b8c1-895a2a59f768.png">

**Comment by taycaldwell** [comment]
Are you using Coinbase Wallet SDK or a third party library?

Can you provide a code snippet?

**Comment by jeongmincho** [comment]
hi @amrap030, have you initialized the CB Wallet SDK with the JSON RPC URL for mumbai? and did you pass the provider into the frontend library? if you're directly calling a provider via web3/ethers, you'll have to specify the RPC URL with the provider you pass into those libraries. 

you won't be able to utilize our "default RPC URL" on the extension itself if you are fetching the balance directly from the dapp via your own provider. a code snippet of your setup will be helpful to debug here. thanks!

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
