### ISSUE TITLE
Bug: Unable to define appLogoUrl

### ISSUE THREAD

**Issue by homeyong** [coinbase/coinbase-wallet-sdk#610]
### Describe the bug

Unable to define appLogoUrl for coinbase browser extension

### Steps

1. Go to https://codesandbox.io/s/web3modal-demo-forked-obbuf5?file=/src/providerOptions.js.
2. Define appLogoUrl, in my example it is twitter.ico
3. Refresh the sandbox browser
4. Click on the Connect > Select Coinbase > noticed that the icon does not change to twitter.
![image](https://user-images.githubusercontent.com/27661534/183003728-02a53452-e2a6-4b0c-9a2d-5381d324da5d.png)

### Expected behavior

The Icon should in the coinbase extension show the logo that defined in appLogoUrl.

### Version

3.0.1

**Comment by prosenjitalpine** [comment]
Any progress on this? I am also getting the same error. Currently, I am seeing a broken image while it Is showing the user permission window. I am using the following code to initialize the `CoinbaseWalletSDK`:

```js
import ethers from "ethers";
import CoinbaseWalletSDK from "@coinbase/wallet-sdk";

const CHAIN_ID = 80001;
// const RPC_URL = ...
// ...
const coinbaseWallet = new CoinbaseWalletSDK({
  appName: "Affine",
  appLogoUrl: "/favicon.io"
});

const ethereum = coinbaseWallet.makeWeb3Provider(RPC_URL, parseInt(CHAIN_ID, 16));

const provider = new ethers.providers.Web3Provider(ethereum);
// ...
```
![image](https://user-images.githubusercontent.com/94828689/192856230-46130bff-d0db-448b-bd63-1d0320b1e1e3.png)


But after the connection has been made, the **Dapp Connections** on the extension is showing the `title` & favicon of that route: 

![image](https://user-images.githubusercontent.com/94828689/192858344-4ae21f4a-1f1f-4944-be80-963e0350bfea.png)

**Comment by gareys-cb** [comment]
Hey! Thanks for reaching out.

If you are still working on this, please try the following:

1. Ensure that your `appLogoUrl` is a complete URL, not a relative path. i.e. `https://mysite.com/logo.png`
2. Provide a browser supported image filetype such as `.png` or `.jpg`. [See the supported filetypes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#supported_image_formats).

We will update our docs to reflect these requirements. Sorry for the confusion.

**Comment by pchy10** [comment]
> Hey! Thanks for reaching out.
> 
> If you are still working on this, please try the following:
> 
> 1. Ensure that your `appLogoUrl` is a complete URL, not a relative path. i.e. `https://mysite.com/logo.png`
> 2. Provide a browser supported image filetype such as `.png` or `.jpg`. [See the supported filetypes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#supported_image_formats).
> 
> We will update our docs to reflect these requirements. Sorry for the confusion.

@gareys-cb I used an external URL as mentioned, but still seeing the same issue. For reference, I am using this URL as `appLogoUrl` value - [https://cdn.affinedefi.com/affine/logo-512x512.png](https://cdn.affinedefi.com/affine/logo-512x512.png)

**Comment by Hlllllllii** [comment]
🇲🇽Sent from my iPhoneOn Feb 6, 2023, at 9:06 AM, Prosenjit Chowdhury ***@***.***> wrote:﻿

Hey! Thanks for reaching out.
If you are still working on this, please try the following:

Ensure that your appLogoUrl is a complete URL, not a relative path. i.e. https://mysite.com/logo.png
Provide a browser supported image filetype such as .png or .jpg. See the supported filetypes.

We will update our docs to reflect these requirements. Sorry for the confusion.

@gareys-cb I used an external URL as mentioned, but still seeing the same issue. For reference, I am using this URL as appLogoUrl value - https://cdn.affinedefi.com/affine/logo-512x512.png

**Comment by CustomerTeam001** [comment]
> ### Describe the bug
> 
> Unable to define appLogoUrl for coinbase browser extension
> 
> ### Steps
> 
> 1. Go to https://codesandbox.io/s/web3modal-demo-forked-obbuf5?file=/src/providerOptions.js.
> 2. Define appLogoUrl, in my example it is twitter.ico
> 3. Refresh the sandbox browser
> 4. Click on the Connect > Select Coinbase > noticed that the icon does not change to twitter.
> ![image](https://user-images.githubusercontent.com/27661534/183003728-02a53452-e2a6-4b0c-9a2d-5381d324da5d.png)
> 
> 
> ### Expected behavior
> 
> The Icon should in the coinbase extension show the logo that defined in appLogoUrl.
> 
> ### Version
> 
> 3.0.1
> 
> ### Additional info
> 
> _No response_
> 
> ### Desktop
> 
> _No response_
> 
> ### Smartphone
> 
> _No response_

We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/VcaSaDQysAwZBQp77

**Comment by CustomerTeam001** [comment]
> Any progress on this? I am also getting a similar kind of error. 
> 
> Currently, I am seeing a broken image while it Is showing the user permission window. I am using the following code to initialize the `CoinbaseWalletSDK`:
> 
> ```js
> import ethers from "ethers";
> import CoinbaseWalletSDK from "@coinbase/wallet-sdk";
> 
> const CHAIN_ID = 80001;
> // const RPC_URL = ...
> // ...
> const coinbaseWallet = new CoinbaseWalletSDK({
>   appName: "Affine",
>   appLogoUrl: "/favicon.io"
> });
> 
> const ethereum = coinbaseWallet.makeWeb3Provider(RPC_URL, parseInt(CHAIN_ID, 16));
> 
> const provider = new ethers.providers.Web3Provider(ethereum);
> // ...
> ```
> ![image](https://user-images.githubusercontent.com/94828689/192856230-46130bff-d0db-448b-bd63-1d0320b1e1e3.png)
> 
> 
> But after the connection has been made, the **Dapp Connections** on the extension is showing the `title` & favicon of that route: 
> 
> ![image](https://user-images.githubusercontent.com/94828689/192858344-4ae21f4a-1f1f-4944-be80-963e0350bfea.png)
> 
> ### Update
> The version I am using is `^3.5.3` for `@coinbase/wallet-sdk` and `^5.6.5` for `ethers`.
> 

We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/VcaSaDQysAwZBQp77

**Comment by rajpraful** [comment]
Could you let me know if this has been resolved?

The tool is taking the favicon url without a / after the domain

eg: MYDOMAIN/assets/favicons/apple-touch-icon-180x180.png should be the url, but it's taking as MYDOMAINassets/favicons/apple-touch-icon-180x180.png
