### ISSUE TITLE
Bug: chainId is incorrect

### ISSUE THREAD

**Issue by agmitron** [coinbase/coinbase-wallet-sdk#612]
### Describe the bug

chainId shows 0x4, when it should be 43113

### Steps

1. Change network in Coinbase Wallet
2. Check `window.ethereum.providers`, find CoinbaseProvider (has property `isWalletLink: true`), check property `chainId`.
3. You can also run ```provider.request({
      method: 'eth_chainId'
    });```, but the result will be the same.

### Expected behavior

On change network in Coinbase property chainId is also changed to the current one.

### Version

3.4.0

### Additional info

My dApp supports only BSC and ETH, and to make my dApp working properly I need to check chainId in wallet before start, and if it's not supported - change it.

![image](https://user-images.githubusercontent.com/44631357/183419253-d53315de-56f1-4399-9d42-2d88ed62f87e.png)
![image](https://user-images.githubusercontent.com/44631357/183419273-3d61f7c0-1400-4bd4-a009-cdef109211a6.png)
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/44631357/183422197-04a1b49b-ff8d-4f11-8858-ae6b95e36fcc.png">

### Desktop

- MacOS 12.1
- Chrome Version 103.0.5060.134 (Official Build) (arm64)

**Comment by shi65** [comment]
bug

**Comment by ccosmincc** [comment]
I'm facing the same issue. Regardless which network I choose, I always get back chainId = 1. Coinbase Wallet desktop extension version 2.31.4.

**Comment by taycaldwell** [comment]
Hi,

The Default Network tab in Coinbase Wallet corresponds to the default network the wallet will connect to when **initially establishing a connection with a dapp**.

Establishing a connection and then switching your default network will not update the chainId.

Instead, to switch your network and update the chainId, make a `wallet_switchEthereumChain` request.
Alternatively, remove the currently established dapp connection within settings, and reconnect with your updated Default Network.

**Comment by Sotatek-HiepNguyen2** [comment]
Same issue here. My app is not working as expected

**Comment by toteto** [comment]
Same incorrect behavior observed on our end, the `chainId` doesn't reflect the selected network on the wallet.

**Comment by CustomerTeam001** [comment]
@ccosmincc @Sotatek-HiepNguyen2 @agmitron 
We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/VcaSaDQysAwZBQp77
