### ISSUE TITLE
Bug: Can't sign a transaction with an external fee payer

### ISSUE THREAD

**Issue by RyanRice02** [coinbase/coinbase-wallet-sdk#642]
### Describe the bug

When attempting to sign a Solana transaction with wallet A (where the fee payer is wallet B) the Chrome browser extension shows "Something went wrong" and logs `Cannot read properties of undefined (reading 'feeCurrencyCode')` to the console.

### Steps

Using two wallets, wallet A (Coinbase Wallet connected via Chrome extension) and wallet B (in–code keypair constructed from private key):
1. Create a new transaction with wallet B set as the fee payer.
2. Add an instruction that sends X tokens from wallet A to wallet B.
3. Partially sign with wallet B and serialize the transaction.
4. Deserialize the transaction and sign with wallet A.

At this point the Chrome extension opens and shows "Something went wrong." If wallet A is set as the fee payer instead, the extension properly shows the transaction for signing.

### Expected behavior

The Chrome extension should present the transaction summary/signing confirmation.

### Additional info

I'm unsure if this is the right repo to open this in as it's a bug with the Coinbase Wallet Chrome extension. If there's a better place to report this, please let me know.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
