### ISSUE TITLE
Feature Request: Support for non-browser access to wallet sdk from a React Native application

### ISSUE THREAD

**Issue by farukparhat** [coinbase/coinbase-wallet-sdk#648]
### Is your feature request related to a problem? Please describe.

Currently, the existing SDK only supports web apps on mobile as it exposes only an in-browser experience for apps to get access to the guest's coinbase wallet.

Other mobile wallet apps such as Phantom also expose a Session based or App to App wallet access API which allows client React Native or mobile iOS/Android apps to perform the following flow:
1. Deeplink into the Wallet Application (Phantom or Coinbase Wallet) with a redirect deeplink back into the client application
2. Client application obtains a session token
3. Client application can then send requests such as signing transactions and messages via deeplinks.

You can find an example application provided by Phantom which implements the above experience
https://github.com/phantom-labs/deep-link-demo-app

### Describe the solution you'd like

- API that lets a mobile application deeplink into the user's coinbase wallet app and then redirect back to the original mobile application.
- Set of APIs (or universal/deep links) which are then callable to facilitate an Mobile App <-> Coinbase Wallet interaction

**Comment by vishnumad** [comment]
Our Mobile Wallet Protocol supports this: https://coinbase.github.io/wallet-mobile-sdk/docs/client-sdk/rn-install
