### ISSUE TITLE
Bug: ReferenceError: intToBuffer is not defined

### ISSUE THREAD

**Issue by DannyFi** [coinbase/coinbase-wallet-sdk#654]
### Describe the bug

ReferenceError: intToBuffer is not defined

### Steps

1. Go to
https://github.com/coinbase/coinbase-wallet-sdk/blob/84ddf4a910d820319a255a75f34d11fdfddffe3c/packages/wallet-sdk/src/vendor-js/eth-eip712-util/util.js#L70

### Expected behavior

intToBuffer is defined

**Comment by bangtoven** [comment]
hi. sorry for the belated response. we are marking stale issues closed for now. please try our latest version 3.6.0. feel free to open a new one if needed. thanks.
