### ISSUE TITLE
@invocamanman reported this issue to the security email address, and we are in the process of paying out a bug bounty. Thank you for the report, @invocamanman

### ISSUE THREAD

**Issue by ytarsha** [coinbase/coinbase-wallet-sdk#675]
@invocamanman reported this issue to the security email address, and we are in the process of paying out a bug bounty. Thank you for the report, @invocamanman

_Originally posted by @moodysalem in https://github.com/Uniswap/v3-staker/issues/219#issuecomment-982827994_

**Comment by tackoman** [comment]
> @invocamanman reported this issue to the security email address, and we are in the process of paying out a bug bounty. Thank you for the report, @invocamanman
> 
> _Originally posted by @moodysalem in [Uniswap/v3-staker#219 (comment)](https://github.com/Uniswap/v3-staker/issues/219#issuecomment-982827994)_
