### ISSUE TITLE
Bug: Error: Failed to sign transaction.

### ISSUE THREAD

**Issue by ArtemFokin** [coinbase/coinbase-wallet-sdk#697]
### Describe the bug

SDK throw this error then i confirm transaction on mumbai network with insufficient balance 

### Steps

Connect your dapp to Wallet app
Keep only 0.1 MATIC
Send transaction where 0.15 MATIC required
Confirm it 
Get unhandled `Error: Failed to sign transaction`,  in your dapp

Error: Failed to sign transaction
    at WalletSDKRelay.js:433:1
    at WalletSDKRelay.invokeCallback (WalletSDKRelay.js:560:1)
    at WalletSDKRelay.handleWeb3ResponseMessage (WalletSDKRelay.js:549:1)
    at Object.next (WalletSDKRelay.js:521:1)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:266:1)
    at SafeSubscriber.next (Subscriber.ts:208:1)
    at Subscriber._next (Subscriber.ts:140:1)
    at Subscriber.next (Subscriber.ts:100:1)
    at MapSubscriber._next (map.ts:90:1)
    at Subscriber.next (Subscriber.ts:100:1)

### Expected behavior

Same error as in Chrome extension app with code INSUFFICIENT_FUNDS

Why even dapp should get this error? I think it would be better if Extension or Wallet App disable buttons if user have not enough balance for operation.

### Version

3.5.3

### Desktop

  System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 695.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 15.5
  npmPackages:
    @coinbase/wallet-sdk: ^3.5.3 => 3.5.3 

### Smartphone

iphone 11
ios 15.5
app version: 28.10.0

**Comment by bangtoven** [comment]
hi. thanks for reporting it. 
we are planning on improving error surfacing. cc @vishnumad 
we will make sure to provide standard errors properly.
