### ISSUE TITLE
Bug: Request method wallet_watchAsset is not supported

### ISSUE THREAD

**Issue by ArtemFokin** [coinbase/coinbase-wallet-sdk#721]
### Describe the bug

if coinbase extension enabled i get this error, if only metamask - works wwell

### Steps

Enable coinbase extension and metamask
just open any site and paste this piece of code in console
```javascript
ethereum.request({
    method: 'wallet_watchAsset',
    params: {
      type: 'ERC20',
      options: {
        address: '0xb60e8dd61c5d32be8058bb8eb970870f07233155',
        symbol: 'FOO',
        decimals: 18,
        image: 'https://foo.io/token-image.svg',
      },
    },
  })
```
you should receive error: `Request method wallet_watchAsset is not supported`

then disable coinbase and try again - should work

### Expected behavior

should work as metamask

**Comment by vishnumad** [comment]
Make sure you are calling `ethereum.request({ method: 'eth_requestAccounts', params: [] })` first before making any RPC calls. I was able to reproduce the error you were seeing when in a disconnected state. After calling `eth_requestAccounts`, the `wallet_watchAsset` call should work.

**Comment by ArtemFokin** [comment]
I'm using wagmi.js and before i called `wallet_watchAsset` i had called transaction request and of course account was connected. 
Here minimal sample for reproducing 
https://codesandbox.io/s/hidden-snow-f66okv?file=/src/App.jsx
pls note what if some of coinbase or metamask extensions disabled  - import works well
If both enabled - i receive errors

**Comment by vishnumad** [comment]
Gotcha, will take another look next week

**Comment by Maryo77** [comment]
require 'coinbase/wallet'

client = Coinbase::Wallet::Client.new(api_key: <api key>,
                                      api_secret: <api secret>,
                                      CB_VERSION: 'YYYY-MM-DD')
payment_methods = client.payment_methods
puts payment_methods

**Comment by Maryo77** [comment]
BNB Wallet ...59c625

**Comment by bangtoven** [comment]
hi. sorry for the belated response.
i tried using both coinbase wallet and metamask installed on my browser, and it's working fine on my end.
please try our latest SDK version 3.6.0. feel free to open a new one if needed. thanks.

**Comment by mwx27** [comment]
> @vishnumad reopen pls I'm using wagmi.js and before i called `wallet_watchAsset` i had called transaction request and of course account was connected. Here minimal sample for reproducing https://codesandbox.io/s/hidden-snow-f66okv?file=/src/App.jsx pls note what if some of coinbase or metamask extensions disabled - import works well If both enabled - i receive errors

Hi @ArtemFokin I think I have nice solution for you!
If you are using wagmi, don't use window.ethereum. You can just use watchAsset method of connector taken for instance from useAccount.

Example below:

  const { connector } = useAccount()
  const addToken = async () => {
    await connector?.watchAsset?.({ address, symbol, decimals, image })
  }
  
  Cheers :)
