### ISSUE TITLE
Feature Request: Use the repo to receive and send tokens via different chains.

### ISSUE THREAD

**Issue by zydjohnHotmail** [coinbase/coinbase-wallet-sdk#749]
### Is your feature request related to a problem? Please describe.

Hello:
I want to know how to use this wallet SDK in Node.js (Version 19.1.0)
First, I want to know if I can receive tokens from one network, and send the tokens to another address via another network.
One example is: if I want to receive some USDT via ERC20 network, then I want to send the received USDT, less the gas fees to another address via BEP20 network.
If it is possible, then show me some basic Node.js code for doing this.

### Describe the solution you'd like

const data = await wallet.getBalance({
    address: '0x2455eC6700092991Ce0782365A89d5Cd89c8Fa22',
    network: 'ethereum',
    rpcUrl: 'https://1rpc.io/eth',
  });

const transfer = await wallet.transfer({
  recipientAddress: '0x2455eC6700092991Ce0782365A89d5Cd89c8Fa22',
  amount: 10,
  network: 'ethereum',
  rpcUrl: 'https://1rpc.io/bnb', => BEP20 RPC URL
  privateKey: 'private key',
  tokenAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7', => USDT contract address
});

### Describe alternatives you've considered

Need some feed back.

### Additional context

I tried to install SDK using npm for the latest version 3.6.2.
But look at the output, I saw a lot of deprecated packages.

D:\nodejs\CoinbaseWallet>npm install @coinbase/wallet-sdk
npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 882 packages, and audited 883 packages in 1m

58 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Is it possible to update all the packages?
By the way, can I use this package without becoming a customer for Coinbase exchange?
Thanks,

**Comment by bangtoven** [comment]
hi. sorry for the belated response. 
to send assets to a different network, you need to use bridges.
we are working on updating our sdk to replace deprecated dependencies. 
thanks.
