### ISSUE TITLE
Bug: Cannot use with react 18.2.0

### ISSUE THREAD

**Issue by chaitanyapotti** [coinbase/coinbase-wallet-sdk#757]
### Describe the bug

Unable to use the sdk with react 18.2.0

### Steps

Using the app with React 18.2.0 causes an error. (https://reactjs.org/warnings/invalid-hook-call-warning.html)
This happens because coinbase sdk pins the usage of `@solana/web3.js` version which uses react-native-polyfill-url which pins react version to 18.1.0

Install with npm to reproduce this error.

### Expected behavior

It should work
To fix, please update to a later version of @solana/web3.js which doesn't have this dependency on react-native-polyfill-url

### Version

latest

**Comment by cb-jake** [comment]
Thanks for reporting. We will look into this.

**Comment by bangtoven** [comment]
hi @chaitanyapotti thanks for reporting it. we just published 3.6.3 which doesn't import `react-native-polyfill-url` anymore. can you try it please
