### ISSUE TITLE
Bug: `connected` and `isConnected()` always return `true`

### ISSUE THREAD

**Issue by toteto** [coinbase/coinbase-wallet-sdk#799]
### Describe the bug

The `CoinbaseWalletProvider` is always reporing as conected regardless whethers it is actually conntected to a DApp or not

### Steps

1. Initialize the CoinbaseWalletSDK
2. Make `CoinbaseWalletProvider with `coinbaseWalletSdk.makeWeb3Provider(...)`
3. Try to get the connected state with either `connected` or `isConnected`
4. Both return `true` always. 

### Expected behavior

The SDK return `false` when there is no connection established between the DApp and the wallet application

### Additional info

https://github.com/coinbase/coinbase-wallet-sdk/blob/84ddf4a910d820319a255a75f34d11fdfddffe3c/packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts#L222-L228

**Comment by bangtoven** [comment]
thanks for reporting this @toteto .
@cb-jake @jeongmincho , i am not sure whether these props are in js provider standard. can we just remove them?

**Comment by cb-jake** [comment]
[EIP-1193#connectivity](https://eips.ethereum.org/EIPS/eip-1193#connectivity)
> The Provider is said to be “connected” when it can service RPC requests to at least one chain.
> The Provider is said to be “disconnected” when it cannot service RPC requests to any chain at all.

One thing we should rely on is provider errors to state when the chain or provider is disconnected. We could leverage walletlink sessions to validate the connection. This might require moving the check into the relays.

Status code | Name | Description
-- | -- | --
4900 | Disconnected | The Provider is disconnected from all chains.
4901 | Chain Disconnected | The Provider is not connected to the requested chain.

**Comment by toteto** [comment]
@cb-jake thanks for your answer. Just to be clear, even though the EIP-1193 is big vague about how it defines connectivity, the expected behavior for `is/connected` field/method would be to return `true` if it is fully connected to a wallet with account?

**Comment by cb-jake** [comment]
@toteto Yes, I believe we should populate the value based on whether the wallet is connected or not.

**Comment by InitialSupport** [comment]
We'd be happy to look into this for you.
Kindly file a support ticket here
https://forms.gle/xABEcR5MwDBJAm1c6

**Comment by sam41306061** [comment]
@toteto is this issue still open?

**Comment by toteto** [comment]
Haven't checked yet, still using 3.6.3, haven't updated to latest to check.

**Comment by bangtoven** [comment]
please try sdk 4.0
