### ISSUE TITLE
Bug: `jsonRpcUrl` is required for there to be QR Code in the connect UI

### ISSUE THREAD

**Issue by toteto** [coinbase/coinbase-wallet-sdk#800]
### Describe the bug

When `undefined` is provided to the `jsonRpcUrl` paramter to the `CoinbaseWalletProvider` the QR Code is not shown in the modal

### Steps

1. Create `CoinbaseWalletSDK`
2. Create `CoinbaseWalletProvider` with providing `undefined` for the `jsonRpcUrl` parameter
3. The show UI doesn't have the top portion that contains the QR codes to connect with wallet apps.

### Expected behavior

There are QR codes to connect with the wallet apps.

If this parameter is required for certain functionalities, please describe them in the docs so the DApp developers are aware of this. 

### Additional info

When providing dummy value (`"dummy"`) the QR codes are shown and the SDK and provider can be connected.

**Comment by bangtoven** [comment]
hi again. thanks for reporting the issue.
this is expected behavior: to connect the dapp with mobile wallet for signing, it needs to have own rpc url on the desktop. we will update the doc accordingly. cc @taycaldwell

**Comment by toteto** [comment]
Thanks for your answer on the issue.

> to connect the dapp with mobile wallet for signing, it needs to have own rpc url on the desktop.

Under "sign" you mean sign transaction and put in on the chain? Because in my testing, using the personal sign method is working correctly even without `jsonRpcUrl`.
