### ISSUE TITLE
Bug: deprecated sub-dependencies

### ISSUE THREAD

**Issue by oumar-fall** [coinbase/coinbase-wallet-sdk#810]
### Describe the bug

The package is using a past version of eth-json-rpc-filters which uses deprecated dependencies

### Steps

According to the dependencies tree:
- @coinbase/wallet-sdk: 3.6.3
    - eth-json-rpc-filters: 4.2.2
        - eth-json-rpc-middleware: ^6.0.0
            - eth-sig-util: ^1.4.2 (Deprecated in favor of '@metamask/eth-sig-util')
                - ethereumjs-abi: "git+https://github.com/ethereumjs/ethereumjs-abi.git" (The package is deprecated and the specified version doesn't match the expected checksum)

### Expected behavior

The package should use the last versino of `eth-json-rpc-filters` (5.1.0), where the dependency `eth-json-rpc-middleware` has been removed

### Version

3.6.3

### Additional info

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/60975029/214542821-8e4eb901-b4b8-4a77-857e-606a0aa49ee2.png">

**Comment by bangtoven** [comment]
addressed. thanks for reporting.
