### ISSUE TITLE
Bug: websocket error 1006

### ISSUE THREAD

**Issue by AdamK222** [coinbase/coinbase-wallet-sdk#812]
### Describe the bug

webSocket.onclose(@coinbase/wallet-sdk/dist/connection/RxWebSocket)

### Steps

In my app I'm using connectkit@1.1.3 and some weird error happens for a lot of them. I don't know if this is something to be worry about and why exactly it is happening so I will show all info I have. I saw it in Sentry.io:

Error webSocket.onclose(@coinbase/wallet-sdk/dist/connection/RxWebSocket)
websocket error 1006
![image](https://user-images.githubusercontent.com/66825147/216037716-48851eee-5c01-4b34-bf4e-00a010cddf63.png)
Handled: Yes
Browser: Chrome 108.0.0
Os: Windows 10

### Expected behavior

Ideally not show this error or explanation why is it happening.

Thanks for any ideas you have :)

### Version

3.6.3

### Desktop

Browser: Chrome 108.0.0
Os: Windows 10
Website: https://20lab.app/

**Comment by bangtoven** [comment]
hi @AdamK222 
were you using extension wallet or mobile wallet with qr code scanning?

**Comment by AdamK222** [comment]
I suppose it was QR code scanning

**Comment by deiay** [comment]
I'm getting this error as well with "@coinbase/wallet-sdk": "3.5.4" being used via "wagmi": "0.11.7". It happens as soon as the page loads, without even making an interactions with coinbase-sdk:
![Kapture 2023-03-04 at 14 50 02](https://user-images.githubusercontent.com/7328115/222932149-1b5186e3-b48d-4220-983a-0463b8f40696.gif)

**Comment by claritise** [comment]
One of my users is getting this error too

**Comment by deiay** [comment]
The issue for me turned out to be that I was erroneously instantiating the wagmi client multiple times. I was able to fix this issue by moving my wagmi config outside of my react context


**Before**
```tsx
pages/_app.tsx

function MyApp({ Component, pageProps }: AppProps) {
	const router = useRouter()

        // Wagmi client
         const { provider } = configureChains(chains, [
	    walletConnectProvider({
		projectId,
	    }),
          ])
          const wagmiClient = createClient({
	          autoConnect: true,
	          connectors: modalConnectors({
		          projectId,
		          version: '1', // or "2"
		          appName,
		          chains,
	          }),
	            provider,
            })

	return (
		<>
                 ...
```
With this, the wagmi client provider was most likely getting initialized multiple times, which was causing an issue for coinbase sdk somewhere down the line.

**After**
```tsx
pages/_app.tsx

   // Wagmi client
const { provider } = configureChains(chains, [
   walletConnectProvider({
   projectId,
}),
    ])
    const wagmiClient = createClient({
	    autoConnect: true,
	    connectors: modalConnectors({
		    projectId,
		    version: '1', // or "2"
		    appName,
		    chains,
	    }),
	      provider,
      })

function MyApp({ Component, pageProps }: AppProps) {
	const router = useRouter()
	return (
		<>
               ...
```
Works fine, no socket error

**Comment by claritise** [comment]
> 

I am already instantiating the wagmi client at the root and still getting the error. I am using the beta app folder in NextJS 13 however. Does anyone else have a similar setup getting this issue?

**Comment by deiay** [comment]
I have the same setup (Next 13 and node v16.14.0), however, I also have disabled Server side rendering at the root level. Maybe see if adding this works?

```tsx
// src/utils/disable-ssr.tsx
import React, { ReactNode } from "react";
import dynamic from "next/dynamic";

const ComponentWrapper = ({ children }: { children: ReactNode }) => {
  return <>{children}</>;
};

export const DisableSSR = dynamic(() => Promise.resolve(ComponentWrapper), {
  ssr: false,
});

```

```tsx
function MyApp({ Component, pageProps }: AppProps) {
       ....
	return (
		...
		<DisableSSR>
                     <WagmiConfig client={wagmiClient}>
                         <Component />
                     </WagmiConfig>
		</DisableSSR>
       )
}
```

**Comment by mwelche** [comment]
I am also noticing this error in nextjs 12.2.2 and node 16 using wagmi.

**Comment by wangshizebin** [comment]
how to solve this bug? i have met it too
