### ISSUE TITLE
Feature Request: remove external references from package meta data - codeload.github.com

### ISSUE THREAD

**Issue by Durai46** [coinbase/coinbase-wallet-sdk#829]
### Is your feature request related to a problem? Please describe.

Hey Team, we are trying to include wagmi package in our application. While installing this package in our network we are getting network timed out error as it is trying to access one of it's transient dependency from codeload.github.com which is restricted in our network.

Error:
npm ERR! code ETIMEDOUT
npm ERR! network request to https://codeload.github.com/ethereumjs/ethereumjs-abi/tar.gz/ee3994657fa7a427238e6ba92a84d0b529bbcde0 failed, reason: connect ETIMEDOUT 140.82.114.10:443
npm ERR! network This is a problem related to network connectivity.

### Describe the solution you'd like

As we analyzed, it is because of this following line: https://github.com/MetaMask/eth-sig-util/blob/1.x/package.json#L24 that codeload.github.com reference is hardcoded into the package meta data.

We believe, one possible solution for this issue is, if we can upgrade wagmi to have all it's external dependencies within the package instead of using external github references.

**Comment by bangtoven** [comment]
hi @Durai46 
it doesn't seem like our sdk package has dependency on eth-sig-util. (we do have on our examples though cc @taycaldwell )
maybe you'd want to raise this to wagmi or eth-sig-util
thanks
