### ISSUE TITLE
Feature Request: Add an option to force QR code display on mobile browsers

### ISSUE THREAD

**Issue by dszeto** [coinbase/coinbase-wallet-sdk#854]
### Is your feature request related to a problem? Please describe.

When opening the Coinbase Wallet connector on a mobile web browser, it will always redirect to `https://www.coinbase.com/connect-dapp?uri=...`. We are building a dapp that runs on mobile kiosks which allows users to connect their wallet by scanning QR code. The current behavior is prohibiting us from letting Coinbase Wallet users connect to the dapp on the mobile kiosk.

### Describe the solution you'd like

It would be nice to have an option to `CoinbaseWalletSDK` which force it to always display the QR code, such as:

```
export const coinbaseWallet = new CoinbaseWalletSDK({
  appName: APP_NAME,
  appLogoUrl: APP_LOGO_URL,
  darkMode: false,
  showQrCodeOnMobile: true // proposed option
})
```

### Describe alternatives you've considered

According to `WalletSDKRelay.ts` it is possible to use JavaScript to force a change to the browser's user agent to exclude any occurrence of `/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/`, but that seems to be too fragile and may not work across all browsers.

### Additional context

Together with the feature request in #818 , it will allow Coinbase Wallets to be implemented on mobile kiosks with a great end-user experience.

**Comment by bangtoven** [comment]
hi. sorry for the late response.
please try the new `enableMobileWalletLink` flag on our latest beta version, v3.8.x
thanks for your patience.

**Comment by Ashoat** [comment]
I'm trying to get Coinbase Wallet to work in our mobile SIWE flow via Rainbowkit.

I can't seem to get `enableMobileWalletLink` to work when I pass it in via Wagmi. We're able to deep link into the Coinbase Wallet app, but nothing shows up once we're there.

Any advice?

https://github.com/coinbase/coinbase-wallet-sdk/assets/863579/cad3d2dd-35c4-4246-b845-e0032b5342d6
