### ISSUE TITLE
Bug: ConnectKit Fails to Connect to Coinbase wallet on 3.6.5

### ISSUE THREAD

**Issue by scotthconner** [coinbase/coinbase-wallet-sdk#860]
### Describe the bug

Console error "process not defined"

### Steps

Use Wagmi, ConnectKit, and Coinbase/wallet-sdk version 3.6.5.

Try to connect to coinbase. It fails with this error:

`mutation.ts:261 ReferenceError: process is not defined
    at node_modules/util/util.js (util.js:109:1)
    at __require2 (chunk-JZQ37OGZ.js?v=c077d2ea:18:50)
    at node_modules/safe-event-emitter/index.js (index.js:1:14)
    at __require2 (chunk-JZQ37OGZ.js?v=c077d2ea:18:50)
    at node_modules/eth-block-tracker/src/base.js (base.js:3:26)
    at __require2 (chunk-JZQ37OGZ.js?v=c077d2ea:18:50)
    at node_modules/eth-block-tracker/src/polling.js (polling.js:2:26)
    at __require2 (chunk-JZQ37OGZ.js?v=c077d2ea:18:50)
    at node_modules/@coinbase/wallet-sdk/dist/provider/SubscriptionManager.js (SubscriptionManager.js:4:29)
    at __require2 (chunk-JZQ37OGZ.js?v=c077d2ea:18:50)`

The same code works against coinbase wallet sdk version 3.5.3. I can't find anyone else reporting this issue.

I might be doing something wrong, but the code is essentially identical.

### Expected behavior

I would expect the browser extension to connect to the dapp.

### Version

3.6.5

### Desktop

Mac OS
Chrome

**Comment by scotthconner** [comment]
Github where it works:  https://github.com/scotthconner/locksmith/blob/main/src/App.js#L91 
"wagmi": "^0.6.7",
"connectkit": "^0.0.2",
"coinbase/wallet-sdk": "3.5.3",

Github where it doesnt:
https://github.com/LocksmithWallet/locksmith-app/blob/main/src/main.jsx#L31
"wagmi": "^0.12.8"
"connectkit": "^1.2.2"
"coinbase/wallet-sdk": "3.6.5",

It is effectively the same code, just updated dependencies. The second project uses vite instead of CRA, but generally the connectkit integration remained untouched, save for some network configuration organization. The first project works at locksmithwallet.com just fine, but the second project fails when developing locally. I cannot for the life of me see the difference.

**Comment by bangtoven** [comment]
thanks for sharing them @scotthconner 
we will take a look.
the error message you got, `process is not defined` sounds like something to do with node.js <> browser though...
btw, the line it failed on `SubscriptionManager` hasn’t been changed ~2 years, and it's been using the same version of `eth-block-tracker` ever since. strange...

**Comment by bangtoven** [comment]
seems like node.js util is missing on vite.
can you try something like https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2

**Comment by scotthconner** [comment]
This actually isn't the issue. What's interesting is once I get the code off my local box, connecting using Coinbase works on mobile. I've also had other folks successfully use Coinbase Wallet on this code base.

There seems to be some internal state in my chrome extension that is causing this issue. I don't know how to further debug this. I have enough wallets in my Chrome extension I'm not particularly motivated to uninstall and re-install unless its somehow easy to restore the entire thing.

I worry that other folks might find themselves in this state, rendering their own installation of coinbase wallet unable to be used in dapps.

**Comment by bangtoven** [comment]
hey @scotthconner 
we just published a new version, 3.6.6, and believe it should fix your issue as well.
please update and let us know if you have any more issues.
