### ISSUE TITLE
Feature Request: i cant find websocket kline api

### ISSUE THREAD

**Issue by keene-dalveytech** [coinbase/coinbase-wallet-sdk#862]
### Is your feature request related to a problem? Please describe.

I am a transaction developer and need to use the websocket api of coinbase kline but I can't find it. Can you help me?

### Describe the solution you'd like

I'm sorry, there are a lot of abandoned warehouses, and I don't know where to ask

**Comment by brianchitester** [comment]
Hi @keene-dalveytech, unfortunately this is not the correct place to ask, this repo is for the coinbase wallet sdk.  It sounds like you're looking for help with [coinbase cloud apis](https://docs.cloud.coinbase.com/) (possibly [this one](https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_getproductcandles)?)

If you can't find what you're looking for there, you can try asking your question in the [dev forums](https://forums.coinbasecloud.dev/).
