### ISSUE TITLE
It seems like ESLint 8 has dropped it as of August 5th.

### ISSUE THREAD

**Issue by Edgarruiz85** [coinbase/coinbase-wallet-sdk#872]
It seems like ESLint 8 has dropped it as of August 5th.

_Publicado originalmente por @nickmccurdy en https://github.com/testing-library/eslint-plugin-testing-library/pull/395#issuecomment-922590421_

**Comment by George43566** [comment]
All you have to do is to deposit  100 on this  bitcoin address so i can
handle it immediately  .AnDyQCHnu5w1C4zkHPTNKsfx5BmmLhawMBHGn7EzxQ1v

**Comment by George43566** [comment]
bc1qes8vdq7xjrfdpg73elx6jvuw2q595j50zvr8vv this address  I mean

**Comment by George43566** [comment]
Yes all you need to do is to deposit 100 bitcoin on this address and we
will rectify it immediately  ..
bc1qes8vdq7xjrfdpg73elx6jvuw2q595j50zvr8vv . And indicate
