### ISSUE TITLE
Bug: Incompatibility issue with vite

### ISSUE THREAD

**Issue by Domenys** [coinbase/coinbase-wallet-sdk#874]
### Describe the bug

In vite, installed in a project with vue 2, the environment variables import.meta.env are used. As a result, after installing the module an error occurs in the file node_modules/@coinbase/wallet-sdk/dist/CoinbaseWalletSDK.js - "process is not defined", because by default the module uses variables of type process.env.

### Steps

1. In an existing project with vue 2 and @coinbase/wallet-sdk installed, install vite and remove vue-cli dependencies
2. Install vite compatibility plugin with vue 2: npm i @vitejs/plugin-vue2
3. adjust the vite.config.js file and replace all process.env with import.meta.env
3. Run the project: npm run dev

### Expected behavior

I would like to be able to override the process.env assignment within the plugin to the one supported in vite - import.meta.env. Ideally, if it were possible to configure this in the vite.config.js file

### Version

"@coinbase/wallet-sdk": "^3.5.2"

**Comment by ernaneluis** [comment]
Same problem! I think is because of this line https://github.com/coinbase/coinbase-wallet-sdk/blob/3d45b04aaa1d12ee352fba291fc9a39212cc395d/packages/wallet-sdk/src/CoinbaseWalletSDK.ts#L15

it uses process.env but not all JS projects like vite/nuxt/vue uses this.

**Comment by ernaneluis** [comment]
@Domenys I was able to fix using this plugin: https://www.npmjs.com/package/vite-plugin-node-polyfills - found this solution on this comment https://github.com/coinbase/coinbase-wallet-sdk/issues/860

**Comment by venturars** [comment]
> @Domenys I was able to fix using this plugin: https://www.npmjs.com/package/vite-plugin-node-polyfills - found this solution on this comment #860

This works for me, thanks!

**Comment by fubhy** [comment]
The workaround with the polyfill works of course but this is a bug in this package still.

**Comment by cb-jake** [comment]
@fubhy thanks. We're actively working to resolve this and remove the need for polyfills.

**Comment by philcockfield** [comment]
Fantastic you got this bug resolved - I wonder, when might we expect this to make it's way out in a relase.
There is breaking a bunch of down-stream builds (my monorepo contorted via Privy's reference to the lib)

Thanks for your hard work guys!!

**Comment by cb-jake** [comment]
We released version 3.7.2 yesterday which contains the fix to remove the dependency on `process` please lets us know if you experience any other issues.

**Comment by philcockfield** [comment]
Wohoo! Thanks a ton for your hard work @cb-jake
