### ISSUE TITLE
Bug:  "confirm on phone" snackbar coming even though it is connected with web extension not over mobile

### ISSUE THREAD

**Issue by satishrapid** [coinbase/coinbase-wallet-sdk#878]
### Describe the bug

coinbase bug "confirm on phone" snackbar coming even though it is connected with web extension not over mobile

### Steps

1) connect with coinbase 
2) do some transaction and after deactivate 
3) again try to connect it show "confirm on phone" snackbar.
<img width="1440" alt="Screenshot 2023-06-05 at 4 13 42 PM" src="https://github.com/coinbase/coinbase-wallet-sdk/assets/82157294/4e7f66c6-fde6-4647-b6d1-c5479aebfa08">

### Expected behavior

if the coinbase is connected through the chrome extension then coinbase connect popup should appear not confirm on phone.

### Version

3.6.6

### Desktop

macOS chrome

**Comment by bangtoven** [comment]
it's been addressed on the latest extension version. thanks.
