### ISSUE TITLE
Bug: Coinbase Wallet cannot detect account change on other tab

### ISSUE THREAD

**Issue by jyeoniii** [coinbase/coinbase-wallet-sdk#906]
### Describe the bug

Coinbase Wallet cannot detect account change on other tab

### Steps

1. Connect Coinbase Wallet and check `coinbaseWalletExtension._addresses` on console. -> Address **A**
2. Switch to other tab, and change the account -> Address **B**
3. Switch back to the previous window, and check `coinbaseWalletExtension._addresses` again -> Retrieved address = **A**

### Expected behavior

Step 3 returns address **B**. (Metamask works like this)

### Version

3.7.1

### Desktop

- OS: Mac OS
- Browser: Chrome 113.0.5672.92

**Comment by bangtoven** [comment]
seems to be issue on the cbwallet extension. reported to the corresponding team. thanks.
