### ISSUE TITLE
Bug: Personal sign sometimes fails with [4001] User denied message signature

### ISSUE THREAD

**Issue by rho-cassiopeiae** [coinbase/coinbase-wallet-sdk#914]
### Describe the bug

In Coinbase Wallet browser extension for Chrome personal_sign sometimes fails with 4001

### Steps

```js      
var signature = await provider.request({
    method: "personal_sign",
    params: [data, account], // data is hex-encoded utf8
});
````

Sometimes calling this function fails with 4001 for no reason. Simply repeating the call eventually succeeds. Sometimes on the very next try, sometimes it takes a few. I certainly do not deliberately decline to sign, so the error message makes no sense.

### Expected behavior

Personal sign succeeds.

### Desktop

- Chrome
- Extension version: 3.25.3_0

**Comment by EstherRhew** [comment]
hi.. I am experiencing same problem.. but the signing fails (as if the user denied) only on full screen (macbook). Is it the same case for you?

**Comment by ppong** [comment]
I am experiencing this problem on a macbook and signing fails and says user rejected even though I did not reject signing. It works 1/3 times - I usually just retry a couple of times :(

**Comment by rho-cassiopeiae** [comment]
I am on Windows fullscreen.

**Comment by bangtoven** [comment]
hi. sorry for the late response. this issue has been fixed a while ago. can you try out our latest version?

**Comment by tre-dev** [comment]
@bangtoven I am having the same issue with the Coinbase Wallet Extension - v3.62.2. Sometimes it throws the error while the extension is opening up the signing.
