### ISSUE TITLE
Bug: wallet_switchEthereumChain doesn't switch to a chain added manually through wallet UI

### ISSUE THREAD

**Issue by rho-cassiopeiae** [coinbase/coinbase-wallet-sdk#915]
### Describe the bug

wallet_switchEthereumChain doesn't switch to a chain added manually through wallet UI, but switches successfully when the chain is added programmatically with wallet_addEthereumChain

### Steps

```js
    try {
      await provider.request({
        method: "wallet_switchEthereumChain",
        params: [{ chainId: "0x385" }],
      });
    } catch (switchError) {
      // 4902
      if (switchError.code === -32603) {
        try {
          await provider.request({
            method: "wallet_addEthereumChain",
            params: [
              {
                chainId: "0x385",
                chainName: "Optimism Local",
                rpcUrls: ["http://localhost:9545"],
                nativeCurrency: {
                  name: "Ether",
                  symbol: "ETH",
                  decimals: 18,
                },
              },
            ],
          });
        } catch (addError) {
          return addError;
        }
      } else {
          return switchError;
      }
    }
```

If I first add the Optimism Local chain manually through UI and then try to execute this code, switch chain fails, even though the chain is there.

If I don't add the chain manually, then the first time the code is executed it fails as expected, since the chain is not present, and then offers to add the chain. Once programmatically added, the second time the code executes, the switching succeeds.

Also as you can see from the code, the error code for when trying to switch to an unknown chain is reported as -32603 for some reason, when it should be 4902.

### Expected behavior

Switching succeeds.

### Desktop

- Chrome
- Extension version: 3.25.3_0

**Comment by bangtoven** [comment]
sorry for the late response.
it's addressed with this PR https://github.com/coinbase/coinbase-wallet-sdk/pull/954 and we will release new version soon. thanks.

**Comment by SamWilsn** [comment]
Looks like this has popped up again.

**Comment by bangtoven** [comment]
please try sdk 4.0
