### ISSUE TITLE
coinbase wallet sdk includes solana/web3.js in my non solana app

### ISSUE THREAD

**Issue by TimDaub** [coinbase/coinbase-wallet-sdk#946]
### Describe the bug

solana included

### Steps

npm ls 

> web@0.0.0 /Users/timdaub/Projects/attestate/kiwistand/src/web
└─┬ wagmi@0.12.13
  └─┬ @wagmi/core@0.10.11
    └─┬ @wagmi/connectors@0.3.19
      └─┬ @coinbase/wallet-sdk@3.6.6
        └─┬ @solana/web3.js@1.77.2
          └─┬ jayson@3.7.0
            └── lodash@4.17.21

### Expected behavior

it must not include it in my bundle

### Version

see above

**Comment by LuisLopez44431** [comment]
So you are the first one right

**Comment by Jessicafreeman1** [comment]
Ok yes


Sent from Yahoo Mail for iPhone


On Thursday, July 27, 2023, 4:47 PM, LuisLopez44431 ***@***.***> wrote:




So you are the first one right

**Comment by LuisLopez44431** [comment]
What to help what are you saying honey

**Comment by LuisLopez44431** [comment]
Ok is tha end buddy can explain

**Comment by LuisLopez44431** [comment]
So now what are you guys think tha is going to happened I don't have or involve in all this so god is perfectly perfect.

**Comment by bangtoven** [comment]
hi. sorry for the late response. we are working on this and it will be removed soon.

**Comment by LuisLopez44431** [comment]
Cuestion is that you are that having access to this accounts end way?
