### ISSUE TITLE
Bug: Arc browser. extension asking for password every time

### ISSUE THREAD

**Issue by Yuripetusko** [coinbase/coinbase-wallet-sdk#976]
### Describe the bug

On Arc browser, password is not remembered and extension is asking to enter password every time a tx needs to be signed

### Steps

1. Install Coinbase Wallet chrome extension on Arc browser
2. Connect wallet to dapp
3. Try to sign any tx, the extension will ask for password
4. Try to sign any tx again, the extension will ask for password again

Only happens on Arc.

Please note that this is older version of wagmi, that uses 3.6.6 version of coinbase wallet sdk.

### Expected behavior

Extension to remember the password. Other wallet extensions doesn't seem to have this problem on Arc

### Version

3.6.6

### Desktop

- Mac OS (Desktop)
- Arc Browser

**Comment by bangtoven** [comment]
seems to be issue on the cbwallet extension. reported to the corresponding team. thanks.
