### ISSUE TITLE
Bug: not working with Angular 16 : process is not defined 

### ISSUE THREAD

**Issue by csurbier** [coinbase/coinbase-wallet-sdk#983]
### Describe the bug

error in console.log of the browser. Project is not launching

### Steps

After install the sdk with npm and importing it in my Angular 16 project, i have an : 

Uncaught ReferenceError: process is not defined
    at 2928 (CoinbaseWalletSDK.js:13:22)

`
import CoinbaseWalletSDK from'@coinbase/wallet-sdk'

export const coinbaseWallet = new CoinbaseWalletSDK({
  appName: "My app",
  appLogoUrl: "",
  darkMode: false
})

`
 
Packages

"@angular/common": "^16.1.0",
    "@angular/compiler": "^16.1.0",
    "@angular/core": "^16.1.0",
    "@angular/forms": "^16.1.0",
    "@angular/platform-browser": "^16.1.0",
    "@angular/platform-browser-dynamic": "^16.1.0",
    "@angular/router": "^16.1.0",
    "@coinbase/wallet-sdk": "^3.7.1",

### Expected behavior

The app should launched and should be able to see the coinbase wallet in my app.

For info, same SDK/code is working on my Angular 14 project.

### Version

3.7.1

### Desktop

Browser : Chrome, Opera

**Comment by csurbier** [comment]
didn't see it but i think it's related to 
https://github.com/coinbase/coinbase-wallet-sdk/issues/967

**Comment by bangtoven** [comment]
we are in the process of removing unnecessary polyfills. thanks.
